use crate::common::AnyType;
use crate::error::Result;
use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;
use std::{
    fs,
    path::{Path, PathBuf},
};

use crate::launcher::Name;

/// Represents a node instance at runtime. Used by RuntimeConfig to identify the running node and its configuration
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct NodeInstanceConfig {
    pub instance_id: Name,
    #[serde(default)]
    pub arguments: BTreeMap<String, AnyType>,
    #[serde(default)]
    pub framework: ResolvedFramework,
}

/// Framework knobs already resolved by the daemon. Distinct from
/// `launcher::FrameworkOverrides` so the type system enforces "resolution
/// happens once": the launcher form carries optional overrides; this form
/// carries concrete values the spawned node reads without further fallback.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ResolvedFramework {
    #[serde(default)]
    pub use_sim_time: bool,
}

/// Configuration for the launcher to know how to configure spawned nodes' messaging.
/// This is passed as part of a LauncherRequest.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct LauncherRuntimeConfig {
    pub messaging_host: String,
    pub messaging_port: u16,
    #[serde(default)]
    pub git_hash: String,
}

impl LauncherRuntimeConfig {
    pub fn new(
        messaging_host: impl Into<String>,
        messaging_port: u16,
        git_hash: impl Into<String>,
    ) -> Self {
        Self {
            messaging_host: messaging_host.into(),
            messaging_port,
            git_hash: git_hash.into(),
        }
    }
}

/// Default variant baseline for runtime configs. Mirrors
/// `node_stack::DEFAULT_VARIANT` (kept locally to avoid an upward crate
/// dependency from `config-internal`).
pub const DEFAULT_VARIANT: &str = "default";

fn default_variant() -> String {
    DEFAULT_VARIANT.to_owned()
}

/// This class is generated by the peppy daemon and then passed to each respective peppy node instances spawned by it
/// through `PEPPY_RUNTIME_CONFIG` env var. It's then deserialized in the process runtime to understand
/// how to communicate with the rest of the system.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct RuntimeConfig {
    pub messaging_host: String,
    pub messaging_port: u16,
    pub node_name: Name,
    pub bound_core_node: Name,
    /// Variant label of the running node. Always populated; bare
    /// `name:tag` adds resolve to [`DEFAULT_VARIANT`]. Generated emitters
    /// read this to populate the variant slot in topic / service / action
    /// key expressions.
    #[serde(default = "default_variant")]
    pub variant: String,
    pub node_instance: NodeInstanceConfig,
}

impl RuntimeConfig {
    pub fn new(
        messaging_host: &str,
        messaging_port: u16,
        node_instance: NodeInstanceConfig,
        node_name: impl Into<String>,
        bound_core_node: impl Into<String>,
        variant: impl Into<String>,
    ) -> Result<Self> {
        Ok(Self {
            messaging_host: messaging_host.to_owned(),
            messaging_port,
            node_instance,
            node_name: Name::new(node_name.into())?,
            bound_core_node: Name::new(bound_core_node.into())?,
            variant: variant.into(),
        })
    }

    /// This function is typically invoked by the `peppy` program
    /// to persist its launch configuration for `peppylib` or `peppygen` to pick it up.
    pub fn save_json5_launch_config(&self, to_path: impl AsRef<Path>) -> Result<PathBuf> {
        let path = to_path.as_ref();
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent)?;
        }

        let serialized = serde_json5::to_string(self)
            .map_err(|err| crate::error::Error::Serialize(err.to_string()))?;
        fs::write(path, serialized)?;
        Ok(path.to_path_buf())
    }

    pub fn generate_peppy_config_fingerprint(peppy_config: impl AsRef<Path>) -> Result<String> {
        use sha2::{Digest, Sha256};
        let config_path = peppy_config.as_ref();
        let content = std::fs::read(config_path)?;
        let hash = Sha256::digest(&content);
        Ok(hash
            .iter()
            .fold(String::with_capacity(hash.len() * 2), |mut acc, b| {
                use std::fmt::Write;
                let _ = write!(acc, "{:02x}", b);
                acc
            }))
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::error::{Error, ParsingError};
    use tempfile::TempDir;

    fn runtime_config_from_json(instance_id: &str) -> Result<RuntimeConfig> {
        let json = r#"{
            messaging_host: "$MESSAGING_HOST",
            messaging_port: $MESSAGING_PORT,
            node_instance: {
                instance_id: "$INSTANCE_ID"
            },
            node_name: "camera",
            bound_core_node: "core_node"
        }"#;

        let populated = json
            .replace("$INSTANCE_ID", instance_id)
            .replace("$MESSAGING_HOST", "127.0.0.1")
            .replace("$MESSAGING_PORT", "7448");
        serde_json5::from_str(&populated).map_err(|err| Error::Parsing(err.into()))
    }

    /// `use_sim_time` round-trips through serialize/deserialize, and a
    /// runtime config that omits the `framework` key parses with
    /// `use_sim_time = false`.
    #[test]
    fn resolved_framework_round_trip_and_default() {
        let with_sim: RuntimeConfig = serde_json5::from_str(
            r#"{
                messaging_host: "127.0.0.1",
                messaging_port: 7448,
                node_instance: {
                    instance_id: "camera_front",
                    framework: { use_sim_time: true }
                },
                node_name: "camera",
                bound_core_node: "core_node"
            }"#,
        )
        .unwrap();
        assert!(with_sim.node_instance.framework.use_sim_time);

        let serialized = serde_json5::to_string(&with_sim).unwrap();
        let reparsed: RuntimeConfig = serde_json5::from_str(&serialized).unwrap();
        assert!(reparsed.node_instance.framework.use_sim_time);

        let omitted = runtime_config_from_json("camera_front").unwrap();
        assert!(!omitted.node_instance.framework.use_sim_time);
    }

    /// A runtime config that omits the `variant` key resolves to
    /// [`DEFAULT_VARIANT`]; a config with an explicit variant round-trips
    /// that exact label.
    #[test]
    fn variant_round_trip_and_default_baseline() {
        let omitted = runtime_config_from_json("camera_front").unwrap();
        assert_eq!(omitted.variant, DEFAULT_VARIANT);

        let with_variant: RuntimeConfig = serde_json5::from_str(
            r#"{
                messaging_host: "127.0.0.1",
                messaging_port: 7448,
                node_instance: { instance_id: "camera_front" },
                node_name: "camera",
                bound_core_node: "core_node",
                variant: "realsense_d405"
            }"#,
        )
        .unwrap();
        assert_eq!(with_variant.variant, "realsense_d405");

        let serialized = serde_json5::to_string(&with_variant).unwrap();
        let reparsed: RuntimeConfig = serde_json5::from_str(&serialized).unwrap();
        assert_eq!(reparsed.variant, "realsense_d405");
    }

    #[test]
    fn writes_launch_config_and_creates_parent_dir() {
        let dir = TempDir::new().unwrap();
        let path = dir.path().join("nested").join("peppy_launcher.json5");

        let config = runtime_config_from_json("camera_front").expect("runtime config should parse");
        let returned = config
            .save_json5_launch_config(&path)
            .expect("runtime config should write");

        let written = fs::read_to_string(&path).expect("launch config should be written to disk");
        let parsed: RuntimeConfig =
            serde_json5::from_str(&written).expect("launch config should parse");

        assert_eq!(returned, path);
        assert_eq!(parsed.node_name, "camera");
        assert_eq!(parsed.node_instance.instance_id, "camera_front");
        assert_eq!(parsed.bound_core_node, "core_node");
        assert_eq!(
            parsed.node_instance.instance_id,
            config.node_instance.instance_id
        );
        assert!(parsed.node_instance.arguments.is_empty());
    }

    #[test]
    fn rejects_invalid_instance_id() {
        let dir = TempDir::new().unwrap();
        let path = dir.path().join("peppy_launcher.json5");

        let err = runtime_config_from_json("bad id!")
            .and_then(|config| config.save_json5_launch_config(&path))
            .unwrap_err();
        assert!(
            matches!(err, Error::Parsing(ParsingError::CannotParseConfig(ref msg)) if msg.contains("Invalid name"))
                || matches!(err, Error::Parsing(ParsingError::InvalidName(_, _))),
            "expected parsing error about invalid name, got: {err}"
        );
    }
}
