[package]
name = "pmi"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
config = { path = "../config-internal" }
askama = "0.15"
bytes = "1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.47", features = ["sync", "rt"] }
tracing = "0.1"
derive_more = { version = "2", features = ["from"] }
tempfile = "3"

# Optional deps
zenoh = { version = "1.5", optional = true }

[build-dependencies]
build-helpers = { path = "../build-helpers-internal" }
zip = { version = "8", default-features = false, features = ["deflate"] }

[dev-dependencies]
tokio = { version = "1.47", features = [
    "sync",
    "rt",
    "macros",
    "time",
    "test-util",
] }
serde_json5 = "0.2"

[features]
default = ["zenoh"]
# Feature to enable zenoh messaging backend
zenoh = ["dep:zenoh"]
# Feature to download the pre-built zenohd binary from GitHub releases
build_zenoh = ["zenoh"]
