[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "arm_controller"
version = "0.1.0"
description = "arm_controller peppy node"
requires-python = ">=3.11,<3.14"
dependencies = ["peppygen"]

[project.scripts]
arm_controller = "arm_controller.__main__:main"

[tool.hatch.build.targets.wheel]
packages = ["src/arm_controller"]

[dependency-groups]
dev = []

[tool.uv.sources]
peppygen = { path = ".peppy/libs/peppygen" }
