//! The thin MCP server node emitted from a validated exposure.
//!
//! [`generate_exposure_node`] turns an exposure document plus its resolved
//! contracts into a complete, buildable node crate: the `peppy.json5`
//! declaring one `depends_on.contracts` slot per logical target, the
//! committed exposure bundle, the per-member bridges between canonical JSON
//! and the peppygen typed clients (topics, services, and action-backed
//! tasks), and a `main` composing the shared `peppy-mcp-runtime` crate. The
//! node carries no hand-written code; everything protocol-shaped lives in
//! the runtime crate, and regeneration happens only when the exposure
//! changes.

mod convert;
#[cfg(test)]
mod tests;

use crate::generator::exposure::bundle::{ExposureBundle, TaskEntry};
use crate::generator::exposure::validate::{
    ExposureValidationError, ResolvedContractDocument, build_exposure_bundle, find_action,
    find_service, find_topic,
};
use crate::generator::rust::identifiers::{
    consumed_action_type_prefix, consumed_service_struct_prefix, sanitize_rust_identifier,
};
use crate::generator::rust::type_mapping::render_tokens;
use config::node::MessageFormat;
use convert::{format_to_json_expr, object_from_json_expr};
use daemon_config::contract::PeppyContract;
use daemon_config::mcp_exposure::McpExposure;
use proc_macro2::{Ident, Literal, Span, TokenStream};
use quote::{format_ident, quote};
use serde_json::json;

/// Default port of the generated endpoint; the launcher overrides it per
/// instance with `arguments: { port: ... }`.
const DEFAULT_PORT: u16 = 8900;

/// One file of the generated node, with a path relative to the node
/// directory (always `/`-separated).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GeneratedFile {
    pub path: String,
    pub content: String,
}

/// The complete generated MCP server node.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GeneratedServerNode {
    /// The directory the node is published under, next to its exposure
    /// document: the node's name.
    pub node_dir_name: String,
    pub files: Vec<GeneratedFile>,
}

/// Validate `exposure` against `contracts` and emit its MCP server node.
///
/// Everything [`build_exposure_bundle`] refuses is refused here too.
pub fn generate_exposure_node(
    exposure: &McpExposure,
    contracts: &[ResolvedContractDocument],
) -> Result<GeneratedServerNode, ExposureValidationError> {
    let bundle = build_exposure_bundle(exposure, contracts)?;
    Ok(generate_exposure_node_from_bundle(
        &bundle, exposure, contracts,
    ))
}

/// Emit the node files for a bundle already built from `exposure` and
/// `contracts`, so a caller needing both artifacts validates only once.
pub fn generate_exposure_node_from_bundle(
    bundle: &ExposureBundle,
    exposure: &McpExposure,
    contracts: &[ResolvedContractDocument],
) -> GeneratedServerNode {
    let files = vec![
        GeneratedFile {
            path: "peppy.json5".to_string(),
            content: render_peppy_json5(bundle),
        },
        GeneratedFile {
            path: "Cargo.toml".to_string(),
            content: render_cargo_toml(bundle),
        },
        GeneratedFile {
            path: ".gitignore".to_string(),
            content: GITIGNORE.to_string(),
        },
        GeneratedFile {
            path: "src/main.rs".to_string(),
            content: render_main_rs(bundle),
        },
        GeneratedFile {
            path: "src/bridges.rs".to_string(),
            content: render_bridges_rs(bundle, exposure, contracts),
        },
        GeneratedFile {
            path: "src/bundle.json".to_string(),
            content: bundle.to_json_string(),
        },
    ];
    GeneratedServerNode {
        node_dir_name: bundle.node.name.clone(),
        files,
    }
}

/// `.peppy/` is materialized by `peppy node sync`; `Cargo.lock` depends on
/// registry state at build time, so neither belongs to the published node.
const GITIGNORE: &str = "/.peppy/\n/target/\n/Cargo.lock\n";

fn generated_header(bundle: &ExposureBundle, file_role: &str) -> String {
    format!(
        "//! Generated MCP server node `{}:{}` for exposure `{}:{}`: {file_role}.\n//! \
         Regenerated by `peppy repo exposure`; do not edit by hand.\n\n",
        bundle.node.name, bundle.node.tag, bundle.exposure.name, bundle.exposure.tag
    )
}

fn render_peppy_json5(bundle: &ExposureBundle) -> String {
    let contracts: Vec<serde_json::Value> = bundle
        .node
        .contracts
        .iter()
        .map(|pin| {
            json!({
                "name": pin.name,
                "tag": pin.tag,
                "link_id": pin.link_id,
                "sha256": pin.sha256,
            })
        })
        .collect();

    let consumed = |target: &str, member: &str| json!({ "link_id": target, "name": member });
    let topic_consumes: Vec<serde_json::Value> = bundle
        .resources
        .iter()
        .map(|resource| consumed(&resource.target, &resource.member))
        .collect();
    let service_consumes: Vec<serde_json::Value> = bundle
        .tools
        .iter()
        .map(|tool| consumed(&tool.target, &tool.member))
        .collect();
    let action_consumes: Vec<serde_json::Value> = bundle
        .tasks
        .iter()
        .map(|task| consumed(&task.target, &task.member))
        .collect();

    let mut interfaces = serde_json::Map::new();
    if !topic_consumes.is_empty() {
        interfaces.insert("topics".to_string(), json!({ "consumes": topic_consumes }));
    }
    if !service_consumes.is_empty() {
        interfaces.insert(
            "services".to_string(),
            json!({ "consumes": service_consumes }),
        );
    }
    if !action_consumes.is_empty() {
        interfaces.insert(
            "actions".to_string(),
            json!({ "consumes": action_consumes }),
        );
    }

    let document = json!({
        "peppy_schema": "node/v1",
        "manifest": {
            "name": bundle.node.name,
            "tag": bundle.node.tag,
            "depends_on": { "contracts": contracts },
        },
        "interfaces": interfaces,
        "execution": {
            "language": "rust",
            "build_cmd": ["cargo", "build", "--release"],
            "run_cmd": [format!("./target/release/{}", bundle.node.name)],
            "parameters": {
                "port": { "$type": "u16", "$default": DEFAULT_PORT },
            },
        },
    });
    let rendered = json5_pretty::to_string_pretty(&document).expect("the node document serializes");
    format!(
        "// Generated MCP server node for exposure `{}:{}`.\n// Regenerated by `peppy repo \
         exposure`; do not edit by hand.\n{rendered}\n",
        bundle.exposure.name, bundle.exposure.tag
    )
}

fn render_cargo_toml(bundle: &ExposureBundle) -> String {
    format!(
        r#"# Generated MCP server node for exposure `{}:{}`.
# Regenerated by `peppy repo exposure`; do not edit by hand.
[package]
name = "{}"
version = "0.1.0"
edition = "2024"

# Detach from any enclosing cargo workspace; the node builds standalone.
[workspace]

[dependencies]
peppygen = {{ path = ".peppy/libs/peppygen" }}
peppylib = {{ path = ".peppy/libs/peppylib" }}
peppy-mcp-runtime = {{ path = ".peppy/libs/peppy-mcp-runtime" }}
serde_json = "1"
tokio = {{ version = "1", features = ["full"] }}
tokio-util = "0.7"
tracing = "0.1"
"#,
        bundle.exposure.name, bundle.exposure.tag, bundle.node.name
    )
}

/// The `consumed_topics`/`consumed_services` module segments for a member.
fn member_module_idents(target: &str, member: &str) -> (Ident, Ident) {
    (
        Ident::new(&sanitize_rust_identifier(target), Span::call_site()),
        Ident::new(&sanitize_rust_identifier(member), Span::call_site()),
    )
}

/// The bridge function ident for one catalog entry: `{kind}_{target}_{member}`.
fn bridge_ident(kind: &str, target: &str, member: &str) -> Ident {
    format_ident!(
        "{kind}_{}_{}",
        sanitize_rust_identifier(target),
        sanitize_rust_identifier(member)
    )
}

fn render_main_rs(bundle: &ExposureBundle) -> String {
    let tool_registrations: Vec<TokenStream> = bundle
        .tools
        .iter()
        .map(|tool| {
            let name_literal = Literal::string(&tool.name);
            let bridge = bridge_ident("tool", &tool.target, &tool.member);
            quote! {
                .with_tool(#name_literal, {
                    let node_runner = std::sync::Arc::clone(&node_runner);
                    move |input: serde_json::Value| {
                        let node_runner = std::sync::Arc::clone(&node_runner);
                        async move { bridges::#bridge(&node_runner, input).await }
                    }
                })
            }
        })
        .collect();

    let task_registrations: Vec<TokenStream> = bundle
        .tasks
        .iter()
        .map(|task| {
            let name_literal = Literal::string(&task.name);
            let bridge = bridge_ident("task", &task.target, &task.member);
            quote! {
                .with_task(#name_literal, {
                    let node_runner = std::sync::Arc::clone(&node_runner);
                    move |input: serde_json::Value, context: peppy_mcp_runtime::ActionContext| {
                        let node_runner = std::sync::Arc::clone(&node_runner);
                        async move { bridges::#bridge(&node_runner, input, context).await }
                    }
                })
            }
        })
        .collect();

    let pumps: Vec<TokenStream> = bundle
        .resources
        .iter()
        .map(|resource| {
            let resource_literal = Literal::string(&resource.name);
            let (link, member) = member_module_idents(&resource.target, &resource.member);
            let bridge = bridge_ident("topic", &resource.target, &resource.member);
            quote! {
                {
                    let ingest = server
                        .ingest(#resource_literal)
                        .expect("the bundle exposes this resource");
                    let node_runner = std::sync::Arc::clone(&node_runner);
                    tokio::spawn(async move {
                        let mut subscription = match peppygen::consumed_topics::#link::#member::subscribe(
                            &node_runner,
                        )
                        .await
                        {
                            Ok(subscription) => subscription,
                            Err(error) => {
                                tracing::warn!(
                                    %error,
                                    resource = #resource_literal,
                                    "subscription failed; the resource stays unavailable"
                                );
                                return;
                            }
                        };
                        loop {
                            match subscription.next().await {
                                Ok(Some((_producer, message))) => {
                                    // The update-rate gate runs before any
                                    // conversion or transcoding work.
                                    let Some(token) = ingest.admit() else { continue };
                                    match bridges::#bridge(message) {
                                        Ok(value) => {
                                            if let Err(error) = ingest.publish(token, value) {
                                                tracing::debug!(
                                                    %error,
                                                    resource = #resource_literal,
                                                    "snapshot refused by policy"
                                                );
                                            }
                                        }
                                        Err(error) => tracing::debug!(
                                            %error,
                                            resource = #resource_literal,
                                            "message does not convert"
                                        ),
                                    }
                                }
                                Ok(None) => break,
                                Err(error) => {
                                    tracing::warn!(
                                        %error,
                                        resource = #resource_literal,
                                        "subscription ended with an error"
                                    );
                                    break;
                                }
                            }
                        }
                    });
                }
            }
        })
        .collect();

    let tokens = quote! {
        mod bridges;

        use peppygen::{NodeBuilder, Parameters, Result};

        const BUNDLE_JSON: &str = include_str!("bundle.json");

        fn main() -> Result<()> {
            NodeBuilder::new().run(|args: Parameters, node_runner| async move {
                peppygen::clock::init(&node_runner).await?;
                let bundle = peppy_mcp_runtime::catalog::ExposureBundle::from_json_str(BUNDLE_JSON)
                    .expect("the committed bundle parses");
                let server = peppy_mcp_runtime::ExposureServer::builder(bundle)
                    .with_clock(peppy_mcp_runtime::Clock::from_nanos_fn(|| {
                        peppygen::clock::now_ns().unwrap_or_default()
                    }))
                    #(#tool_registrations)*
                    #(#task_registrations)*
                    .build()
                    .expect("the committed bundle and the generated bridges agree");
                #(#pumps)*
                let listener =
                    match tokio::net::TcpListener::bind(("127.0.0.1", args.port)).await {
                        Ok(listener) => listener,
                        Err(error) => panic!("cannot bind 127.0.0.1:{}: {error}", args.port),
                    };
                let shutdown = tokio_util::sync::CancellationToken::new();
                {
                    let shutdown = shutdown.clone();
                    node_runner.on_shutdown(async move {
                        shutdown.cancel();
                    });
                }
                tokio::spawn(server.serve(listener, shutdown));
                Ok(())
            })
        }
    };
    format!(
        "{}{}",
        generated_header(bundle, "endpoint setup"),
        render_tokens(tokens)
    )
}

fn render_bridges_rs(
    bundle: &ExposureBundle,
    exposure: &McpExposure,
    contracts: &[ResolvedContractDocument],
) -> String {
    let mut items: Vec<TokenStream> = Vec::new();

    for resource in &bundle.resources {
        let contract = contract_for(exposure, contracts, &resource.target);
        let declared = find_topic(contract, &resource.member)
            .expect("the bundle only carries members the contract declares");
        let format = declared.message_format.clone().unwrap_or_default();
        let (link, member) = member_module_idents(&resource.target, &resource.member);
        let bridge = bridge_ident("topic", &resource.target, &resource.member);
        let to_json = format_to_json_expr(&format, quote!(message));
        items.push(quote! {
            pub(crate) fn #bridge(
                message: peppygen::consumed_topics::#link::#member::Message,
            ) -> std::result::Result<serde_json::Value, String> {
                Ok(#to_json)
            }
        });
    }

    for tool in &bundle.tools {
        let contract = contract_for(exposure, contracts, &tool.target);
        let declared = find_service(contract, &tool.member)
            .expect("the bundle only carries members the contract declares");
        let request_format = effective_format(declared.request_message_format.as_ref());
        let response_format = effective_format(declared.response_message_format.as_ref());
        let (link, member) = member_module_idents(&tool.target, &tool.member);
        let module = quote!(peppygen::consumed_services::#link::#member);
        let bridge = bridge_ident("tool", &tool.target, &tool.member);
        let deadline_literal = Literal::u64_unsuffixed(tool.deadline_ms.get());
        let service_prefix = consumed_service_struct_prefix(&tool.member);

        let request_fn = format_ident!("{bridge}_request");
        let response_fn = format_ident!("{bridge}_response");

        if let Some(format) = request_format {
            let from_json = object_from_json_expr(
                &format.0,
                quote!(input),
                &module,
                "Request",
                &service_prefix,
                0,
            );
            items.push(quote! {
                fn #request_fn(
                    input: &serde_json::Value,
                ) -> std::result::Result<#module::Request, String> {
                    Ok(#from_json)
                }
            });
        }
        if let Some(format) = response_format {
            let to_json = format_to_json_expr(format, quote!(data));
            items.push(quote! {
                fn #response_fn(
                    data: #module::ResponseData,
                ) -> std::result::Result<serde_json::Value, String> {
                    Ok(#to_json)
                }
            });
        }

        let request_statement = if request_format.is_some() {
            quote! {
                let request = #request_fn(&input)
                    .map_err(peppy_mcp_runtime::ToolCallError::Failed)?;
            }
        } else {
            quote! {
                let _ = input;
            }
        };
        let poll_arguments = if request_format.is_some() {
            quote!(node_runner, target, deadline, request)
        } else {
            quote!(node_runner, target, deadline)
        };
        let call_statement = if response_format.is_some() {
            quote! {
                let response = #module::poll(#poll_arguments)
                    .await
                    .map_err(|error| peppy_mcp_runtime::ToolCallError::Failed(error.to_string()))?;
                #response_fn(response.data).map_err(peppy_mcp_runtime::ToolCallError::Failed)
            }
        } else {
            quote! {
                #module::poll(#poll_arguments)
                    .await
                    .map_err(|error| peppy_mcp_runtime::ToolCallError::Failed(error.to_string()))?;
                Ok(serde_json::Value::Object(serde_json::Map::new()))
            }
        };

        items.push(quote! {
            pub(crate) async fn #bridge(
                node_runner: &peppygen::NodeRunner,
                input: serde_json::Value,
            ) -> std::result::Result<serde_json::Value, peppy_mcp_runtime::ToolCallError> {
                #request_statement
                let target = #module::bound_producer(node_runner);
                let deadline = std::time::Duration::from_millis(#deadline_literal);
                #call_statement
            }
        });
    }

    for task in &bundle.tasks {
        items.push(render_task_bridge(task, exposure, contracts));
    }

    let tokens = quote! {
        #(#items)*
    };
    format!(
        "{}{}",
        generated_header(
            bundle,
            "bridges between canonical JSON and the typed clients"
        ),
        render_tokens(tokens)
    )
}

/// The bridge behind one action-backed task: fire the goal, pump feedback
/// into the task's status message, forward `tasks/cancel` cooperatively,
/// and map the Peppy terminal result onto the MCP terminal state.
fn render_task_bridge(
    task: &TaskEntry,
    exposure: &McpExposure,
    contracts: &[ResolvedContractDocument],
) -> TokenStream {
    let contract = contract_for(exposure, contracts, &task.target);
    let declared = find_action(contract, &task.member)
        .expect("the bundle only carries members the contract declares");
    let goal_format = effective_format(
        declared
            .goal_service
            .as_ref()
            .and_then(|goal| goal.request_message_format.as_ref()),
    );
    let feedback_format = effective_format(
        declared
            .feedback_topic
            .as_ref()
            .map(|feedback| &feedback.message_format),
    );
    let result_format = effective_format(
        declared
            .result_service
            .as_ref()
            .and_then(|result| result.response_message_format.as_ref()),
    );

    let (link, member) = member_module_idents(&task.target, &task.member);
    let module = quote!(peppygen::consumed_actions::#link::#member);
    let bridge = bridge_ident("task", &task.target, &task.member);
    let deadline_literal = Literal::u64_unsuffixed(task.deadline_ms.get());
    // The Rust backend names the generated action types after the producer
    // (here: the contract) and the action; nested goal structs continue
    // from `{that}ActionGoal`.
    let goal_prefix = format!(
        "{}ActionGoal",
        consumed_action_type_prefix(contract.manifest.name.as_str(), &task.member)
    );

    let goal_fn = format_ident!("{bridge}_goal");
    let feedback_fn = format_ident!("{bridge}_feedback");
    let result_fn = format_ident!("{bridge}_result");

    let mut items: Vec<TokenStream> = Vec::new();
    if let Some(format) = goal_format {
        let from_json = object_from_json_expr(
            &format.0,
            quote!(input),
            &module,
            "GoalRequest",
            &goal_prefix,
            0,
        );
        items.push(quote! {
            fn #goal_fn(
                input: &serde_json::Value,
            ) -> std::result::Result<#module::GoalRequest, String> {
                Ok(#from_json)
            }
        });
    }
    if let Some(format) = feedback_format {
        let to_json = format_to_json_expr(format, quote!(message));
        items.push(quote! {
            fn #feedback_fn(
                message: #module::FeedbackMessage,
            ) -> std::result::Result<serde_json::Value, String> {
                Ok(#to_json)
            }
        });
    }
    if let Some(format) = result_format {
        let to_json = format_to_json_expr(format, quote!(data));
        items.push(quote! {
            fn #result_fn(
                data: #module::ResultResponseData,
            ) -> std::result::Result<serde_json::Value, String> {
                Ok(#to_json)
            }
        });
    }

    let request_statement = if goal_format.is_some() {
        quote! {
            let request = #goal_fn(&input).map_err(peppy_mcp_runtime::ActionExit::Failed)?;
        }
    } else {
        quote! {
            let _ = input;
        }
    };
    let fire_arguments = if goal_format.is_some() {
        quote!(
            node_runner,
            target,
            deadline,
            request,
            peppygen::QoSProfile::SensorData
        )
    } else {
        quote!(
            node_runner,
            target,
            deadline,
            peppygen::QoSProfile::SensorData
        )
    };
    // Only the feedback drain needs the handle mutably.
    let handle_binding = if feedback_format.is_some() {
        quote!(mut handle)
    } else {
        quote!(handle)
    };

    // Cancellation is cooperative on both sides: `tasks/cancel` is
    // forwarded once to the Peppy cancel path, and the terminal result the
    // provider settles on decides the task's terminal state.
    let await_result = if feedback_format.is_some() {
        quote! {
            let mut cancel_pending = false;
            let mut cancel_forwarded = false;
            loop {
                if cancel_pending {
                    cancel_pending = false;
                    cancel_forwarded = true;
                    let _ = handle.cancel_goal(deadline).await;
                }
                tokio::select! {
                    _ = context.cancel_requested(), if !cancel_forwarded => {
                        cancel_pending = true;
                    }
                    message = handle.on_next_feedback_message() => match message {
                        Ok(message) => {
                            if let Ok(value) = #feedback_fn(message) {
                                context.report_feedback(value.to_string());
                            }
                        }
                        // The stream ends at the terminal result (clean
                        // close) or when the producer disappears; either
                        // way the result reply below settles the outcome.
                        Err(_) => break,
                    }
                }
            }
            let result = handle
                .get_result(deadline)
                .await
                .map_err(|error| peppy_mcp_runtime::ActionExit::Failed(error.to_string()))?;
        }
    } else {
        quote! {
            let mut cancel_forwarded = false;
            let result_future = handle.get_result(deadline);
            tokio::pin!(result_future);
            let result = loop {
                tokio::select! {
                    result = &mut result_future => break result,
                    _ = context.cancel_requested(), if !cancel_forwarded => {
                        cancel_forwarded = true;
                        let _ = handle.cancel_goal(deadline).await;
                    }
                }
            }
            .map_err(|error| peppy_mcp_runtime::ActionExit::Failed(error.to_string()))?;
        }
    };

    let completed_arm = if result_format.is_some() {
        quote! {
            #module::ResultOutcome::Completed(data) => {
                #result_fn(data).map_err(peppy_mcp_runtime::ActionExit::Failed)
            }
        }
    } else {
        quote! {
            #module::ResultOutcome::Completed => {
                Ok(serde_json::Value::Object(serde_json::Map::new()))
            }
        }
    };
    let cancelled_pattern = if result_format.is_some() {
        quote!(#module::ResultOutcome::Cancelled(_))
    } else {
        quote!(#module::ResultOutcome::Cancelled)
    };

    items.push(quote! {
        pub(crate) async fn #bridge(
            node_runner: &peppygen::NodeRunner,
            input: serde_json::Value,
            context: peppy_mcp_runtime::ActionContext,
        ) -> std::result::Result<serde_json::Value, peppy_mcp_runtime::ActionExit> {
            #request_statement
            let target = #module::bound_producer(node_runner);
            let deadline = std::time::Duration::from_millis(#deadline_literal);
            let #handle_binding = #module::ActionHandle::fire_goal(#fire_arguments)
                .await
                .map_err(|error| peppy_mcp_runtime::ActionExit::Failed(error.to_string()))?;
            if !handle.accepted {
                return Err(peppy_mcp_runtime::ActionExit::Failed(
                    match handle.reason.as_deref() {
                        Some(reason) => format!("the provider rejected the goal: {reason}"),
                        None => "the provider rejected the goal".to_string(),
                    },
                ));
            }
            #await_result
            match result.outcome {
                #completed_arm
                #cancelled_pattern => Err(peppy_mcp_runtime::ActionExit::Cancelled),
                #module::ResultOutcome::Abandoned => Err(peppy_mcp_runtime::ActionExit::Failed(
                    "the provider abandoned the goal".to_string(),
                )),
                #module::ResultOutcome::Expired => Err(peppy_mcp_runtime::ActionExit::Failed(
                    "the goal expired before reaching a terminal result".to_string(),
                )),
            }
        }
    });

    quote! {
        #(#items)*
    }
}

/// Treats an absent or empty format the way the peppygen backend does: no
/// request struct, or a `()`-returning poll.
fn effective_format(format: Option<&MessageFormat>) -> Option<&MessageFormat> {
    format.filter(|format| !format.0.is_empty())
}

fn contract_for<'a>(
    exposure: &McpExposure,
    contracts: &'a [ResolvedContractDocument],
    target: &str,
) -> &'a PeppyContract {
    let reference = &exposure
        .targets
        .get(target)
        .expect("bundle targets come from the exposure")
        .contract;
    &contracts
        .iter()
        .find(|resolved| {
            resolved.document.manifest.name.as_str() == reference.name.as_str()
                && resolved.document.manifest.tag == reference.tag
        })
        .expect("the bundle only builds when every referenced contract resolves")
        .document
}
