//! Generated MCP server node `camera_observation_mcp:v1` for exposure `camera_observation:v1`: bridges between canonical JSON and the typed clients.
//! Regenerated by `peppy repo exposure`; do not edit by hand.

pub(crate) fn topic_front_camera_video_stream(
    message: peppygen::consumed_topics::front_camera::video_stream::Message,
) -> std::result::Result<serde_json::Value, String> {
    Ok({
        let nested_0 = message;
        let mut object_0 = serde_json::Map::new();
        object_0
            .insert(
                "frame".to_string(),
                serde_json::Value::String(
                    peppy_mcp_runtime::bridge::bytes_to_base64(&nested_0.frame),
                ),
            );
        object_0
            .insert("encoding".to_string(), serde_json::Value::from(nested_0.encoding));
        object_0.insert("width".to_string(), serde_json::Value::from(nested_0.width));
        object_0.insert("height".to_string(), serde_json::Value::from(nested_0.height));
        object_0
            .insert(
                "stamp".to_string(),
                serde_json::Value::String(
                    peppy_mcp_runtime::bridge::time_to_rfc3339(nested_0.stamp),
                ),
            );
        serde_json::Value::Object(object_0)
    })
}
pub(crate) fn topic_front_camera_camera_status(
    message: peppygen::consumed_topics::front_camera::camera_status::Message,
) -> std::result::Result<serde_json::Value, String> {
    Ok({
        let nested_0 = message;
        let mut object_0 = serde_json::Map::new();
        object_0
            .insert("battery".to_string(), serde_json::Value::from(nested_0.battery));
        object_0
            .insert(
                "temperature_c".to_string(),
                peppy_mcp_runtime::bridge::float_to_json(
                    f64::from(nested_0.temperature_c),
                )?,
            );
        object_0
            .insert(
                "frames_captured".to_string(),
                serde_json::Value::String(nested_0.frames_captured.to_string()),
            );
        object_0
            .insert(
                "clock_drift_ns".to_string(),
                serde_json::Value::String(nested_0.clock_drift_ns.to_string()),
            );
        object_0
            .insert(
                "recording".to_string(),
                serde_json::Value::from(nested_0.recording),
            );
        if let Some(value) = nested_0.note {
            object_0.insert("note".to_string(), serde_json::Value::from(value));
        }
        object_0
            .insert(
                "calibrated_at".to_string(),
                serde_json::Value::String(
                    peppy_mcp_runtime::bridge::time_to_rfc3339(nested_0.calibrated_at),
                ),
            );
        object_0
            .insert(
                "checksum".to_string(),
                serde_json::Value::String(
                    peppy_mcp_runtime::bridge::bytes_to_base64(&nested_0.checksum),
                ),
            );
        object_0
            .insert(
                "gains".to_string(),
                {
                    let mut items_1 = Vec::new();
                    for item in nested_0.gains {
                        items_1
                            .push(
                                peppy_mcp_runtime::bridge::float_to_json(f64::from(item))?,
                            );
                    }
                    serde_json::Value::Array(items_1)
                },
            );
        object_0
            .insert(
                "tags".to_string(),
                {
                    let mut items_1 = Vec::new();
                    for item in nested_0.tags {
                        items_1.push(serde_json::Value::from(item));
                    }
                    serde_json::Value::Array(items_1)
                },
            );
        object_0
            .insert(
                "pose".to_string(),
                {
                    let nested_1 = nested_0.pose;
                    let mut object_1 = serde_json::Map::new();
                    object_1
                        .insert(
                            "x_m".to_string(),
                            peppy_mcp_runtime::bridge::float_to_json(nested_1.x_m)?,
                        );
                    object_1
                        .insert(
                            "y_m".to_string(),
                            peppy_mcp_runtime::bridge::float_to_json(nested_1.y_m)?,
                        );
                    serde_json::Value::Object(object_1)
                },
            );
        object_0
            .insert(
                "samples".to_string(),
                {
                    let mut items_1 = Vec::new();
                    for item in nested_0.samples {
                        items_1
                            .push({
                                let nested_2 = item;
                                let mut object_2 = serde_json::Map::new();
                                object_2
                                    .insert(
                                        "offset".to_string(),
                                        serde_json::Value::from(nested_2.offset),
                                    );
                                object_2
                                    .insert(
                                        "value".to_string(),
                                        peppy_mcp_runtime::bridge::float_to_json(nested_2.value)?,
                                    );
                                serde_json::Value::Object(object_2)
                            });
                    }
                    serde_json::Value::Array(items_1)
                },
            );
        serde_json::Value::Object(object_0)
    })
}
fn tool_front_camera_video_stream_info_response(
    data: peppygen::consumed_services::front_camera::video_stream_info::ResponseData,
) -> std::result::Result<serde_json::Value, String> {
    Ok({
        let nested_0 = data;
        let mut object_0 = serde_json::Map::new();
        object_0.insert("width".to_string(), serde_json::Value::from(nested_0.width));
        object_0.insert("height".to_string(), serde_json::Value::from(nested_0.height));
        object_0
            .insert(
                "fps".to_string(),
                peppy_mcp_runtime::bridge::float_to_json(f64::from(nested_0.fps))?,
            );
        object_0.insert("device".to_string(), serde_json::Value::from(nested_0.device));
        serde_json::Value::Object(object_0)
    })
}
pub(crate) async fn tool_front_camera_video_stream_info(
    node_runner: &peppygen::NodeRunner,
    input: serde_json::Value,
) -> std::result::Result<serde_json::Value, peppy_mcp_runtime::ToolCallError> {
    let _ = input;
    let target = peppygen::consumed_services::front_camera::video_stream_info::bound_producer(
        node_runner,
    );
    let deadline = std::time::Duration::from_millis(2000);
    let response = peppygen::consumed_services::front_camera::video_stream_info::poll(
            node_runner,
            target,
            deadline,
        )
        .await
        .map_err(|error| peppy_mcp_runtime::ToolCallError::Failed(error.to_string()))?;
    tool_front_camera_video_stream_info_response(response.data)
        .map_err(peppy_mcp_runtime::ToolCallError::Failed)
}
fn tool_front_camera_set_brightness_request(
    input: &serde_json::Value,
) -> std::result::Result<
    peppygen::consumed_services::front_camera::set_brightness::Request,
    String,
> {
    Ok({
        let input_0 = input;
        peppygen::consumed_services::front_camera::set_brightness::Request {
            value: peppy_mcp_runtime::bridge::value_i32(
                peppy_mcp_runtime::bridge::require(input_0, "value")?,
                "value",
            )?,
        }
    })
}
fn tool_front_camera_set_brightness_response(
    data: peppygen::consumed_services::front_camera::set_brightness::ResponseData,
) -> std::result::Result<serde_json::Value, String> {
    Ok({
        let nested_0 = data;
        let mut object_0 = serde_json::Map::new();
        object_0
            .insert("applied".to_string(), serde_json::Value::from(nested_0.applied));
        serde_json::Value::Object(object_0)
    })
}
pub(crate) async fn tool_front_camera_set_brightness(
    node_runner: &peppygen::NodeRunner,
    input: serde_json::Value,
) -> std::result::Result<serde_json::Value, peppy_mcp_runtime::ToolCallError> {
    let request = tool_front_camera_set_brightness_request(&input)
        .map_err(peppy_mcp_runtime::ToolCallError::Failed)?;
    let target = peppygen::consumed_services::front_camera::set_brightness::bound_producer(
        node_runner,
    );
    let deadline = std::time::Duration::from_millis(2000);
    let response = peppygen::consumed_services::front_camera::set_brightness::poll(
            node_runner,
            target,
            deadline,
            request,
        )
        .await
        .map_err(|error| peppy_mcp_runtime::ToolCallError::Failed(error.to_string()))?;
    tool_front_camera_set_brightness_response(response.data)
        .map_err(peppy_mcp_runtime::ToolCallError::Failed)
}
fn tool_front_camera_calibrate_request(
    input: &serde_json::Value,
) -> std::result::Result<
    peppygen::consumed_services::front_camera::calibrate::Request,
    String,
> {
    Ok({
        let input_0 = input;
        peppygen::consumed_services::front_camera::calibrate::Request {
            exposure_us: peppy_mcp_runtime::bridge::value_u32(
                peppy_mcp_runtime::bridge::require(input_0, "exposure_us")?,
                "exposure_us",
            )?,
            offsets: {
                let items = peppy_mcp_runtime::bridge::value_array(
                    peppy_mcp_runtime::bridge::require(input_0, "offsets")?,
                    "offsets",
                )?;
                let mut out_1 = Vec::with_capacity(items.len());
                for item in items {
                    out_1.push(peppy_mcp_runtime::bridge::value_i16(item, "offsets")?);
                }
                out_1
                    .try_into()
                    .map_err(|_| {
                        format!("`{}` must have exactly {} items", "offsets", 2)
                    })?
            },
            profile: {
                let input_1 = peppy_mcp_runtime::bridge::require(input_0, "profile")?;
                peppygen::consumed_services::front_camera::calibrate::CalibrateProfile {
                    gamma: peppy_mcp_runtime::bridge::value_f64(
                        peppy_mcp_runtime::bridge::require(input_1, "gamma")?,
                        "gamma",
                    )?,
                    white_balance: {
                        let input_2 = peppy_mcp_runtime::bridge::require(
                            input_1,
                            "white_balance",
                        )?;
                        peppygen::consumed_services::front_camera::calibrate::CalibrateProfileWhiteBalance {
                            red: {
                                let wide = peppy_mcp_runtime::bridge::value_f64(
                                    peppy_mcp_runtime::bridge::require(input_2, "red")?,
                                    "red",
                                )?;
                                if !wide.is_finite() || wide < f32::MIN as f64
                                    || wide > f32::MAX as f64
                                {
                                    return Err(
                                        format!(
                                            "`{}` is outside the range of a 32-bit float", "red"
                                        ),
                                    );
                                }
                                wide as f32
                            },
                            blue: {
                                let wide = peppy_mcp_runtime::bridge::value_f64(
                                    peppy_mcp_runtime::bridge::require(input_2, "blue")?,
                                    "blue",
                                )?;
                                if !wide.is_finite() || wide < f32::MIN as f64
                                    || wide > f32::MAX as f64
                                {
                                    return Err(
                                        format!(
                                            "`{}` is outside the range of a 32-bit float", "blue"
                                        ),
                                    );
                                }
                                wide as f32
                            },
                        }
                    },
                }
            },
            comment: match peppy_mcp_runtime::bridge::optional(input_0, "comment") {
                Some(value) => {
                    Some(peppy_mcp_runtime::bridge::value_string(value, "comment")?)
                }
                None => None,
            },
        }
    })
}
pub(crate) async fn tool_front_camera_calibrate(
    node_runner: &peppygen::NodeRunner,
    input: serde_json::Value,
) -> std::result::Result<serde_json::Value, peppy_mcp_runtime::ToolCallError> {
    let request = tool_front_camera_calibrate_request(&input)
        .map_err(peppy_mcp_runtime::ToolCallError::Failed)?;
    let target = peppygen::consumed_services::front_camera::calibrate::bound_producer(
        node_runner,
    );
    let deadline = std::time::Duration::from_millis(10000);
    peppygen::consumed_services::front_camera::calibrate::poll(
            node_runner,
            target,
            deadline,
            request,
        )
        .await
        .map_err(|error| peppy_mcp_runtime::ToolCallError::Failed(error.to_string()))?;
    Ok(serde_json::Value::Object(serde_json::Map::new()))
}
pub(crate) async fn tool_front_camera_ping(
    node_runner: &peppygen::NodeRunner,
    input: serde_json::Value,
) -> std::result::Result<serde_json::Value, peppy_mcp_runtime::ToolCallError> {
    let _ = input;
    let target = peppygen::consumed_services::front_camera::ping::bound_producer(
        node_runner,
    );
    let deadline = std::time::Duration::from_millis(1000);
    peppygen::consumed_services::front_camera::ping::poll(node_runner, target, deadline)
        .await
        .map_err(|error| peppy_mcp_runtime::ToolCallError::Failed(error.to_string()))?;
    Ok(serde_json::Value::Object(serde_json::Map::new()))
}
fn task_recorder_record_episode_goal(
    input: &serde_json::Value,
) -> std::result::Result<
    peppygen::consumed_actions::recorder::record_episode::GoalRequest,
    String,
> {
    Ok({
        let input_0 = input;
        peppygen::consumed_actions::recorder::record_episode::GoalRequest {
            task_description: peppy_mcp_runtime::bridge::value_string(
                peppy_mcp_runtime::bridge::require(input_0, "task_description")?,
                "task_description",
            )?,
        }
    })
}
fn task_recorder_record_episode_feedback(
    message: peppygen::consumed_actions::recorder::record_episode::FeedbackMessage,
) -> std::result::Result<serde_json::Value, String> {
    Ok({
        let nested_0 = message;
        let mut object_0 = serde_json::Map::new();
        object_0.insert("frame".to_string(), serde_json::Value::from(nested_0.frame));
        object_0.insert("phase".to_string(), serde_json::Value::from(nested_0.phase));
        serde_json::Value::Object(object_0)
    })
}
fn task_recorder_record_episode_result(
    data: peppygen::consumed_actions::recorder::record_episode::ResultResponseData,
) -> std::result::Result<serde_json::Value, String> {
    Ok({
        let nested_0 = data;
        let mut object_0 = serde_json::Map::new();
        object_0
            .insert(
                "episode_index".to_string(),
                serde_json::Value::from(nested_0.episode_index),
            );
        serde_json::Value::Object(object_0)
    })
}
pub(crate) async fn task_recorder_record_episode(
    node_runner: &peppygen::NodeRunner,
    input: serde_json::Value,
    context: peppy_mcp_runtime::ActionContext,
) -> std::result::Result<serde_json::Value, peppy_mcp_runtime::ActionExit> {
    let request = task_recorder_record_episode_goal(&input)
        .map_err(peppy_mcp_runtime::ActionExit::Failed)?;
    let target = peppygen::consumed_actions::recorder::record_episode::bound_producer(
        node_runner,
    );
    let deadline = std::time::Duration::from_millis(900000);
    let started = std::time::Instant::now();
    let mut handle = peppygen::consumed_actions::recorder::record_episode::ActionHandle::fire_goal(
            node_runner,
            target,
            deadline,
            request,
            peppygen::QoSProfile::SensorData,
        )
        .await
        .map_err(|error| peppy_mcp_runtime::ActionExit::Failed(error.to_string()))?;
    if !handle.accepted {
        return Err(
            peppy_mcp_runtime::ActionExit::Failed(
                match handle.reason.as_deref() {
                    Some(reason) => format!("the provider rejected the goal: {reason}"),
                    None => "the provider rejected the goal".to_string(),
                },
            ),
        );
    }
    let mut cancel_pending = false;
    let mut cancel_forwarded = false;
    let expiry = tokio::time::sleep(deadline.saturating_sub(started.elapsed()));
    tokio::pin!(expiry);
    loop {
        if cancel_pending {
            cancel_pending = false;
            cancel_forwarded = true;
            let _ = handle.cancel_goal(deadline.saturating_sub(started.elapsed())).await;
        }
        tokio::select! {
            _ = & mut expiry => break, _ = context.cancel_requested(), if !
            cancel_forwarded => { cancel_pending = true; } message = handle
            .on_next_feedback_message() => match message { Ok(message) => { if let
            Ok(value) = task_recorder_record_episode_feedback(message) { context
            .report_feedback(value.to_string()); } } Err(_) => break, }
        }
    }
    let result = handle
        .get_result(deadline.saturating_sub(started.elapsed()))
        .await
        .map_err(|error| peppy_mcp_runtime::ActionExit::Failed(error.to_string()))?;
    match result.outcome {
        peppygen::consumed_actions::recorder::record_episode::ResultOutcome::Completed(
            data,
        ) => {
            task_recorder_record_episode_result(data)
                .map_err(peppy_mcp_runtime::ActionExit::Failed)
        }
        peppygen::consumed_actions::recorder::record_episode::ResultOutcome::Cancelled(
            _,
        ) => Err(peppy_mcp_runtime::ActionExit::Cancelled),
        peppygen::consumed_actions::recorder::record_episode::ResultOutcome::Abandoned => {
            Err(
                peppy_mcp_runtime::ActionExit::Failed(
                    "the provider abandoned the goal".to_string(),
                ),
            )
        }
        peppygen::consumed_actions::recorder::record_episode::ResultOutcome::Expired => {
            Err(
                peppy_mcp_runtime::ActionExit::Failed(
                    "the goal expired before reaching a terminal result".to_string(),
                ),
            )
        }
    }
}
pub(crate) async fn task_recorder_resume_session(
    node_runner: &peppygen::NodeRunner,
    input: serde_json::Value,
    context: peppy_mcp_runtime::ActionContext,
) -> std::result::Result<serde_json::Value, peppy_mcp_runtime::ActionExit> {
    let _ = input;
    let target = peppygen::consumed_actions::recorder::resume_session::bound_producer(
        node_runner,
    );
    let deadline = std::time::Duration::from_millis(30000);
    let started = std::time::Instant::now();
    let handle = peppygen::consumed_actions::recorder::resume_session::ActionHandle::fire_goal(
            node_runner,
            target,
            deadline,
            peppygen::QoSProfile::Standard,
        )
        .await
        .map_err(|error| peppy_mcp_runtime::ActionExit::Failed(error.to_string()))?;
    if !handle.accepted {
        return Err(
            peppy_mcp_runtime::ActionExit::Failed(
                match handle.reason.as_deref() {
                    Some(reason) => format!("the provider rejected the goal: {reason}"),
                    None => "the provider rejected the goal".to_string(),
                },
            ),
        );
    }
    let mut cancel_forwarded = false;
    let result_future = handle.get_result(deadline.saturating_sub(started.elapsed()));
    tokio::pin!(result_future);
    let result = loop {
        tokio::select! {
            result = & mut result_future => break result, _ = context.cancel_requested(),
            if ! cancel_forwarded => { cancel_forwarded = true; let _ = handle
            .cancel_goal(deadline.saturating_sub(started.elapsed())). await; }
        }
    }
        .map_err(|error| peppy_mcp_runtime::ActionExit::Failed(error.to_string()))?;
    match result.outcome {
        peppygen::consumed_actions::recorder::resume_session::ResultOutcome::Completed => {
            Ok(serde_json::Value::Object(serde_json::Map::new()))
        }
        peppygen::consumed_actions::recorder::resume_session::ResultOutcome::Cancelled => {
            Err(peppy_mcp_runtime::ActionExit::Cancelled)
        }
        peppygen::consumed_actions::recorder::resume_session::ResultOutcome::Abandoned => {
            Err(
                peppy_mcp_runtime::ActionExit::Failed(
                    "the provider abandoned the goal".to_string(),
                ),
            )
        }
        peppygen::consumed_actions::recorder::resume_session::ResultOutcome::Expired => {
            Err(
                peppy_mcp_runtime::ActionExit::Failed(
                    "the goal expired before reaching a terminal result".to_string(),
                ),
            )
        }
    }
}
