//! Generated MCP server node `camera_observation_mcp:v1` for exposure `camera_observation:v1`: endpoint setup.
//! Regenerated by `peppy repo exposure`; do not edit by hand.

mod bridges;
use peppygen::{NodeBuilder, Parameters, Result};
const BUNDLE_JSON: &str = include_str!("bundle.json");
fn main() -> Result<()> {
    NodeBuilder::new()
        .run(|args: Parameters, node_runner| async move {
            peppygen::clock::init(&node_runner).await?;
            let bundle = peppy_mcp_runtime::catalog::ExposureBundle::from_json_str(
                    BUNDLE_JSON,
                )
                .expect("the committed bundle parses");
            let server = peppy_mcp_runtime::ExposureServer::builder(bundle)
                .with_clock(
                    peppy_mcp_runtime::Clock::from_nanos_fn(|| {
                        peppygen::clock::now_ns().unwrap_or_default()
                    }),
                )
                .with_tool(
                    "front_camera.info",
                    {
                        let node_runner = std::sync::Arc::clone(&node_runner);
                        move |input: serde_json::Value| {
                            let node_runner = std::sync::Arc::clone(&node_runner);
                            async move {
                                bridges::tool_front_camera_video_stream_info(
                                        &node_runner,
                                        input,
                                    )
                                    .await
                            }
                        }
                    },
                )
                .with_tool(
                    "front_camera.set_brightness",
                    {
                        let node_runner = std::sync::Arc::clone(&node_runner);
                        move |input: serde_json::Value| {
                            let node_runner = std::sync::Arc::clone(&node_runner);
                            async move {
                                bridges::tool_front_camera_set_brightness(
                                        &node_runner,
                                        input,
                                    )
                                    .await
                            }
                        }
                    },
                )
                .with_tool(
                    "front_camera.calibrate",
                    {
                        let node_runner = std::sync::Arc::clone(&node_runner);
                        move |input: serde_json::Value| {
                            let node_runner = std::sync::Arc::clone(&node_runner);
                            async move {
                                bridges::tool_front_camera_calibrate(&node_runner, input)
                                    .await
                            }
                        }
                    },
                )
                .with_tool(
                    "front_camera.ping",
                    {
                        let node_runner = std::sync::Arc::clone(&node_runner);
                        move |input: serde_json::Value| {
                            let node_runner = std::sync::Arc::clone(&node_runner);
                            async move {
                                bridges::tool_front_camera_ping(&node_runner, input).await
                            }
                        }
                    },
                )
                .with_task(
                    "recorder.record_episode",
                    {
                        let node_runner = std::sync::Arc::clone(&node_runner);
                        move |
                            input: serde_json::Value,
                            context: peppy_mcp_runtime::ActionContext|
                        {
                            let node_runner = std::sync::Arc::clone(&node_runner);
                            async move {
                                bridges::task_recorder_record_episode(
                                        &node_runner,
                                        input,
                                        context,
                                    )
                                    .await
                            }
                        }
                    },
                )
                .with_task(
                    "recorder.resume_session",
                    {
                        let node_runner = std::sync::Arc::clone(&node_runner);
                        move |
                            input: serde_json::Value,
                            context: peppy_mcp_runtime::ActionContext|
                        {
                            let node_runner = std::sync::Arc::clone(&node_runner);
                            async move {
                                bridges::task_recorder_resume_session(
                                        &node_runner,
                                        input,
                                        context,
                                    )
                                    .await
                            }
                        }
                    },
                )
                .build()
                .expect("the committed bundle and the generated bridges agree");
            {
                let ingest = server
                    .ingest("front_camera.latest_frame")
                    .expect("the bundle exposes this resource");
                let node_runner = std::sync::Arc::clone(&node_runner);
                tokio::spawn(async move {
                    let mut subscription = match peppygen::consumed_topics::front_camera::video_stream::subscribe(
                            &node_runner,
                        )
                        .await
                    {
                        Ok(subscription) => subscription,
                        Err(error) => {
                            tracing::warn!(
                                % error, resource = "front_camera.latest_frame",
                                "subscription failed; the resource stays unavailable"
                            );
                            return;
                        }
                    };
                    loop {
                        match subscription.next().await {
                            Ok(Some((_producer, message))) => {
                                let Some(token) = ingest.admit() else { continue };
                                match bridges::topic_front_camera_video_stream(message) {
                                    Ok(value) => {
                                        if let Err(error) = ingest.publish(token, value) {
                                            tracing::debug!(
                                                % error, resource = "front_camera.latest_frame",
                                                "snapshot refused by policy"
                                            );
                                        }
                                    }
                                    Err(error) => {
                                        tracing::debug!(
                                            % error, resource = "front_camera.latest_frame",
                                            "message does not convert"
                                        )
                                    }
                                }
                            }
                            Ok(None) => break,
                            Err(error) => {
                                tracing::warn!(
                                    % error, resource = "front_camera.latest_frame",
                                    "subscription ended with an error"
                                );
                                break;
                            }
                        }
                    }
                });
            }
            {
                let ingest = server
                    .ingest("front_camera.status")
                    .expect("the bundle exposes this resource");
                let node_runner = std::sync::Arc::clone(&node_runner);
                tokio::spawn(async move {
                    let mut subscription = match peppygen::consumed_topics::front_camera::camera_status::subscribe(
                            &node_runner,
                        )
                        .await
                    {
                        Ok(subscription) => subscription,
                        Err(error) => {
                            tracing::warn!(
                                % error, resource = "front_camera.status",
                                "subscription failed; the resource stays unavailable"
                            );
                            return;
                        }
                    };
                    loop {
                        match subscription.next().await {
                            Ok(Some((_producer, message))) => {
                                let Some(token) = ingest.admit() else { continue };
                                match bridges::topic_front_camera_camera_status(message) {
                                    Ok(value) => {
                                        if let Err(error) = ingest.publish(token, value) {
                                            tracing::debug!(
                                                % error, resource = "front_camera.status",
                                                "snapshot refused by policy"
                                            );
                                        }
                                    }
                                    Err(error) => {
                                        tracing::debug!(
                                            % error, resource = "front_camera.status",
                                            "message does not convert"
                                        )
                                    }
                                }
                            }
                            Ok(None) => break,
                            Err(error) => {
                                tracing::warn!(
                                    % error, resource = "front_camera.status",
                                    "subscription ended with an error"
                                );
                                break;
                            }
                        }
                    }
                });
            }
            let listener = match tokio::net::TcpListener::bind(("127.0.0.1", args.port))
                .await
            {
                Ok(listener) => listener,
                Err(error) => panic!("cannot bind 127.0.0.1:{}: {error}", args.port),
            };
            let shutdown = tokio_util::sync::CancellationToken::new();
            {
                let shutdown = shutdown.clone();
                node_runner
                    .on_shutdown(async move {
                        shutdown.cancel();
                    });
            }
            tokio::spawn(server.serve(listener, shutdown));
            Ok(())
        })
}
