[package]
name = "peppylib-py"
version.workspace = true
edition.workspace = true

[lib]
name = "_peppylib"
crate-type = ["cdylib"]

[dependencies]
config = { path = "../config-internal" }
peppylib = { path = "../peppylib" }
pmi = { path = "../pmi-internal", features = ["zenoh", "build_zenoh"] }
pythonize = { version = "0.28" }
pyo3 = { version = "0.28", features = ["extension-module", "abi3-py311"] }
pyo3-async-runtimes = { version = "0.28", features = ["tokio-runtime"] }
rand = "0.10"
names-generator2 = "0.2.1"
serde_json = "1"
tokio = { version = "1.47", features = ["rt-multi-thread"] }
parking_lot = { workspace = true }

[build-dependencies]
build-helpers = { path = "../build-helpers-internal" }
pyo3-build-config = "0.28"
