use super::super::action_loop::{ActionResult, ActionState, GoalHandler, run_action_loop};
use super::super::stack::STACK_LAUNCH_GIT_HASH;
use super::sync::{
    self, AutoSyncParams, AutoSyncVariant, collect_consumed_interfaces, generate_peppygen_for_node,
};
use super::{
    checkout_repo_ref, extract_tar_zst, generate_random_id, is_supported_fs_archive,
    is_supported_http_archive, locate_node_root_dir, resolve_local_archive_source,
    sanitize_repo_path, write_error_to_log,
};
use crate::Result;
use crate::encoding::{
    NodeAddFeedback, NodeAddGoal, NodeAddGoalResponse, NodeAddResult, NodeSource,
};
use crate::names;
use chrono::Local;
use config::consts::{NODE_CONFIG_FILE, PEPPY_OUTPUT_DIR, PEPPYGEN_OUTPUT_PATH, PeppyDirs};
use config::node::{DEFAULT_VARIANT_NAME, NodeConfig, NodeConfigParser, ParsedNodeConfig};
use futures::FutureExt;
use git2::build::RepoBuilder;
use node_stack::{BuildContext, NodeStack, validate_dependency_specs};
use peppylib::messaging::{ServiceRequestContext, TopicPublisher};
use peppylib::types::Payload;
use peppylib::{ActionMessenger, MessengerHandle, PeppyResult};
use std::fs::File;
use std::io::{Read, Write};
use std::panic::AssertUnwindSafe;
use std::path::{Path, PathBuf};
use std::process::{Command, Stdio};
use std::sync::{Arc, Mutex as StdMutex};
use std::time::{Duration, Instant};
use tokio::sync::{Mutex, mpsc};
use tokio::task::JoinHandle;
use tracing::debug;
use ureq::Error as HttpError;

use super::{FeedbackLine, FeedbackStream, create_action_log_file, stream_child_output};

pub async fn listen_for_node_add(
    messenger: &MessengerHandle,
    core_node_name: &str,
    instance_id: &str,
    node_name: &str,
    node_stack: Arc<NodeStack>,
    peppy_dirs: PeppyDirs,
) -> Result<JoinHandle<Result<()>>> {
    let action = ActionMessenger::expose(
        messenger,
        core_node_name,
        instance_id,
        node_name,
        names::NODE_ADD_ACTION,
    )
    .await?;

    let handler = NodeAddGoalHandler {
        context: NodeAddActionContext {
            node_stack,
            messenger: messenger.clone(),
            bound_core_node: core_node_name.to_string(),
            core_instance_id: instance_id.to_string(),
            peppy_dirs,
        },
        running_since: Arc::new(Mutex::new(None)),
        running_task: Arc::new(Mutex::new(None)),
    };

    let handle = tokio::spawn(async move { run_action_loop(action, handler).await });

    Ok(handle)
}

impl ActionResult for NodeAddResult {
    fn identifier() -> &'static str {
        "node_add_result"
    }

    fn encode_result(&self) -> crate::Result<Payload> {
        self.encode()
    }
}

#[derive(Clone)]
struct NodeAddGoalHandler {
    context: NodeAddActionContext,
    /// Tracks when the current action started and its timeout, used to format
    /// "action already in progress (times out in Xs)" rejection messages.
    running_since: Arc<Mutex<Option<(Instant, u64)>>>,
    /// Handle to the currently running add task, used to abort it when `--force` is set.
    running_task: Arc<Mutex<Option<JoinHandle<()>>>>,
}

impl GoalHandler for NodeAddGoalHandler {
    type Result = NodeAddResult;

    async fn handle_goal(
        &self,
        context: ServiceRequestContext,
        feedback_publisher: TopicPublisher,
        state: Arc<Mutex<ActionState<NodeAddResult>>>,
    ) -> PeppyResult<Payload> {
        handle_goal_request(
            context,
            feedback_publisher,
            state,
            self.context.clone(),
            Arc::clone(&self.running_since),
            Arc::clone(&self.running_task),
        )
        .await
    }
}

/// Directories excluded from node snapshot copies.
///
/// These are either regenerated by the daemon (`.peppy`) or by the node's
/// `add_cmd` (virtual-environment / package directories). Copying virtual
/// environments breaks Python on macOS because `std::fs::copy` dereferences
/// symlinks, turning `@executable_path`-relative dylib references into
/// dangling paths.
const COPY_EXCLUDED_DIRS_PEPPY: &[&str] = &[".peppy"];

const COPY_EXCLUDED_DIRS_PYTHON: &[&str] = &[
    ".venv",
    ".pixi",
    "__pypackages__",
    "__pycache__",
    ".tox",
    ".nox",
    ".conda",
    ".mypy_cache",
    ".pytest_cache",
    ".ruff_cache",
];

const COPY_EXCLUDED_DIRS_RUST: &[&str] = &["target"];

const COPY_EXCLUDED_DIRS_JS_TS: &[&str] = &[
    "node_modules",
    ".next",
    ".nuxt",
    ".turbo",
    ".parcel-cache",
    ".svelte-kit",
    "bower_components",
];

const COPY_EXCLUDED_DIRS_C: &[&str] = &["build", "cmake-build-debug", "cmake-build-release"];

const COPY_EXCLUDED_DIRS_CPP: &[&str] = &[
    "build",
    "cmake-build-debug",
    "cmake-build-release",
    ".cache",
];

const COPY_EXCLUDED_DIRS_VCS: &[&str] = &[".git"];

const COPY_EXCLUDED_DIRS: &[&[&str]] = &[
    COPY_EXCLUDED_DIRS_PEPPY,
    COPY_EXCLUDED_DIRS_PYTHON,
    COPY_EXCLUDED_DIRS_RUST,
    COPY_EXCLUDED_DIRS_JS_TS,
    COPY_EXCLUDED_DIRS_C,
    COPY_EXCLUDED_DIRS_CPP,
    COPY_EXCLUDED_DIRS_VCS,
];

fn is_excluded_dir(name: &std::ffi::OsStr) -> bool {
    COPY_EXCLUDED_DIRS
        .iter()
        .any(|list| list.iter().any(|&excluded| name == excluded))
}

/// Recursively copies `src` into `dest`, skipping excluded directories.
///
/// Returns the names of top-level excluded directories that were present
/// directly under `src`. Nested skips are not recorded.
fn copy_dir_recursive(src: &Path, dest: &Path) -> Result<Vec<String>> {
    std::fs::create_dir_all(dest)?;

    let mut excluded = Vec::new();

    for entry in std::fs::read_dir(src)? {
        let entry = entry?;
        let file_name = entry.file_name();

        if is_excluded_dir(&file_name) {
            if let Some(name) = file_name.to_str() {
                excluded.push(name.to_owned());
            }
            continue;
        }

        let src_path = entry.path();
        let dest_path = dest.join(file_name);
        let ft = entry.file_type()?;

        if ft.is_symlink() {
            // Skip symlinks to avoid infinite recursion with circular links
            continue;
        } else if ft.is_dir() {
            copy_dir_recursive(&src_path, &dest_path)?;
        } else {
            std::fs::copy(&src_path, &dest_path)?;
        }
    }
    Ok(excluded)
}

/// Expands `${VAR}` references in a string using the provided environment variables.
fn expand_env_vars(s: &str, env_vars: &[(String, String)]) -> String {
    let mut result = s.to_string();
    for (key, value) in env_vars {
        let pattern = format!("${{{}}}", key);
        if result.contains(&pattern) {
            result = result.replace(&pattern, value);
        }
    }
    result
}

/// Runs the add_cmd for a node and streams output via the feedback publisher.
/// Returns Ok(()) if add_cmd is None or executes successfully.
async fn run_add_cmd_with_streaming(
    add_cmd: Option<&Vec<String>>,
    working_dir: &Path,
    env_vars: &[(String, String)],
    feedback_tx: &mpsc::UnboundedSender<FeedbackLine>,
    log_file: Arc<StdMutex<File>>,
) -> std::result::Result<(), String> {
    let Some(cmd) = add_cmd else {
        return Ok(());
    };

    if cmd.is_empty() {
        return Err("add_cmd is empty".to_string());
    };

    // Expand ${VAR} references in add_cmd strings using the injected env vars.
    // This is necessary because multi-element commands are executed directly
    // (not through a shell), so shell-style variable expansion doesn't happen.
    let cmd: Vec<String> = cmd.iter().map(|s| expand_env_vars(s, env_vars)).collect();

    let (program, args) = if cmd.len() == 1 {
        ("sh".to_string(), vec!["-c".to_string(), cmd[0].clone()])
    } else {
        (cmd[0].clone(), cmd[1..].to_vec())
    };

    debug!(
        "Running add_cmd: {} {:?} in dir {:?}",
        program, args, working_dir
    );

    let full_cmd = std::iter::once(program.as_str())
        .chain(args.iter().map(String::as_str))
        .collect::<Vec<_>>()
        .join(" ");

    // Log the command being executed to the log file before attempting to spawn
    {
        if let Ok(mut file) = log_file.lock() {
            let timestamp = Local::now().format("%Y-%m-%dT%H:%M:%S%.3f");
            let _ = writeln!(
                file,
                "[{}] Executing add_cmd: {} (working_dir: {})",
                timestamp,
                full_cmd,
                working_dir.display()
            );
            let _ = file.flush();
        }
    }

    let mut command = Command::new(&program);
    command.args(&args);
    command.current_dir(working_dir);
    command.stdout(Stdio::piped());
    command.stderr(Stdio::piped());
    for (key, value) in env_vars {
        command.env(key, value);
    }
    let child = command
        .spawn()
        .map_err(|e| format!("failed to execute add_cmd `{}`: {}", full_cmd, e))?;

    let (status, _) = stream_child_output(child, feedback_tx, log_file, false).await?;

    if !status.success() {
        return Err(format!(
            "add_cmd `{}` failed with status {}",
            full_cmd, status
        ));
    }

    debug!("add_cmd completed successfully");
    Ok(())
}

/// Copies a node folder to a temporary working directory.
///
/// Returns the path to the temporary directory and the list of top-level
/// directories that were excluded from the copy. The caller is responsible
/// for cleaning up the temporary directory.
fn copy_node_to_temp_dir(from_dir: &Path, tmp_root: &Path) -> Result<(PathBuf, Vec<String>)> {
    std::fs::create_dir_all(tmp_root)?;
    let temp_dir = tempfile::TempDir::new_in(tmp_root)?.keep();

    debug!(
        "Copying node folder from {} to temp dir {}",
        from_dir.display(),
        temp_dir.display()
    );

    let mut excluded = copy_dir_recursive(from_dir, &temp_dir)?;
    excluded.sort();

    Ok((temp_dir, excluded))
}

/// Verifies that the node directory is in sync with the currently running daemon
/// by comparing the stored git hash with the expected one.
///
/// Returns `Ok(())` if verification passes, or `Err(error_message)` if it fails.
fn verify_git_hash(source_path: &Path, expected_git_hash: &str) -> std::result::Result<(), String> {
    let git_hash_path = source_path.join(PEPPY_OUTPUT_DIR).join("git.hash");
    let stored_git_hash = std::fs::read_to_string(&git_hash_path).map_err(|e| {
        format!(
            "Missing required git hash file at {}: {}. Run `peppy node sync` before `peppy node add`.",
            git_hash_path.display(),
            e
        )
    })?;

    let expected_git_hash = expected_git_hash.trim();
    let stored_git_hash = stored_git_hash.trim();

    if stored_git_hash.is_empty() {
        return Err(format!(
            "Invalid git hash file at {}: file is empty. Run `peppy node sync` before `peppy node add`.",
            git_hash_path.display(),
        ));
    }

    if stored_git_hash != expected_git_hash {
        return Err(format!(
            "git hash mismatch for node directory {} (expected '{}', found '{}' in {}). Run `peppy node sync` before retrying.",
            source_path.display(),
            expected_git_hash,
            stored_git_hash,
            git_hash_path.display(),
        ));
    }

    Ok(())
}

pub(super) struct CleanupDir(Option<PathBuf>);

impl CleanupDir {
    pub(super) fn new(dir: Option<PathBuf>) -> Self {
        Self(dir)
    }

    pub(super) fn take(&mut self) -> Option<PathBuf> {
        self.0.take()
    }
}

impl Drop for CleanupDir {
    fn drop(&mut self) {
        if let Some(dir) = self.0.take() {
            std::fs::remove_dir_all(dir).ok();
        }
    }
}

pub(crate) struct ResolvedNodeAddSource {
    pub(crate) source_path: PathBuf,
    pub(crate) node_config: ParsedNodeConfig,
    pub(crate) cleanup_dir: Option<PathBuf>,
}

/// Result of downloading and extracting an HTTP bundle without parsing the node config.
pub(crate) struct ExtractedHttpSource {
    pub(crate) source_path: PathBuf,
    pub(crate) cleanup_dir: Option<PathBuf>,
}

/// Distinguishes between a definitively invalid config (no point doing a full
/// clone) and an infrastructure failure during the shallow probe (fall back to
/// full clone).
enum ShallowCheckError {
    /// The config was found but is invalid — a full clone would fail the same way.
    InvalidConfig(String),
    /// The shallow fetch itself failed (e.g. server doesn't support shallow
    /// clones, network error, ref not found). Fall back to full clone.
    ShallowFetchFailed(String),
}

/// Performs a depth-1 shallow fetch into a bare repo and reads the node config
/// blob directly from the git object database — no working-directory checkout.
fn shallow_validate_config(
    repo_url: &str,
    repo_relative_path: &Path,
    repo_ref: Option<&str>,
) -> std::result::Result<ParsedNodeConfig, ShallowCheckError> {
    let bare_dir = tempfile::tempdir().map_err(|e| {
        ShallowCheckError::ShallowFetchFailed(format!("Failed to create temp dir: {}", e))
    })?;

    let bare_repo = git2::Repository::init_bare(bare_dir.path()).map_err(|e| {
        ShallowCheckError::ShallowFetchFailed(format!("Failed to init bare repo: {}", e))
    })?;

    let mut remote = bare_repo.remote_anonymous(repo_url).map_err(|e| {
        ShallowCheckError::ShallowFetchFailed(format!("Failed to create remote: {}", e))
    })?;

    // Build refspecs to try, in order of preference.
    let refspecs: Vec<String> = match repo_ref {
        None | Some("") => vec!["HEAD".to_string()],
        Some(r) => vec![
            r.to_string(),
            format!("refs/heads/{r}"),
            format!("refs/tags/{r}"),
        ],
    };

    let mut last_err = None;
    for refspec in &refspecs {
        let mut fetch_opts = git2::FetchOptions::new();
        fetch_opts.depth(1);
        fetch_opts.download_tags(git2::AutotagOption::None);

        match remote.fetch(&[refspec.as_str()], Some(&mut fetch_opts), None) {
            Ok(()) => {
                last_err = None;
                break;
            }
            Err(e) => {
                last_err = Some(e);
                // Recreate the remote for a clean retry.
                remote = bare_repo.remote_anonymous(repo_url).map_err(|e2| {
                    ShallowCheckError::ShallowFetchFailed(format!(
                        "Failed to recreate remote: {}",
                        e2
                    ))
                })?;
            }
        }
    }
    if let Some(e) = last_err {
        return Err(ShallowCheckError::ShallowFetchFailed(format!(
            "shallow fetch failed: {}",
            e
        )));
    }

    // Resolve FETCH_HEAD to a commit.
    let fetch_head = bare_repo.find_reference("FETCH_HEAD").map_err(|e| {
        ShallowCheckError::ShallowFetchFailed(format!("Failed to find FETCH_HEAD: {}", e))
    })?;
    let commit = fetch_head.peel_to_commit().map_err(|e| {
        ShallowCheckError::ShallowFetchFailed(format!("Failed to peel to commit: {}", e))
    })?;
    let tree = commit
        .tree()
        .map_err(|e| ShallowCheckError::ShallowFetchFailed(format!("Failed to get tree: {}", e)))?;

    // Navigate the tree to find the config blob.
    let config_tree_path = if repo_relative_path
        .extension()
        .and_then(|ext| ext.to_str())
        .is_some_and(|ext| ext.eq_ignore_ascii_case("json5"))
    {
        repo_relative_path.to_path_buf()
    } else {
        repo_relative_path.join(NODE_CONFIG_FILE)
    };

    let entry = tree.get_path(&config_tree_path).map_err(|e| {
        ShallowCheckError::InvalidConfig(format!(
            "Config file '{}' not found in repository: {}",
            config_tree_path.display(),
            e
        ))
    })?;

    let blob = bare_repo.find_blob(entry.id()).map_err(|e| {
        ShallowCheckError::ShallowFetchFailed(format!("Failed to read config blob: {}", e))
    })?;

    let content = std::str::from_utf8(blob.content()).map_err(|_| {
        ShallowCheckError::InvalidConfig("peppy.json5 is not valid UTF-8".to_string())
    })?;

    NodeConfigParser::from_content(content).map_err(|e| {
        ShallowCheckError::InvalidConfig(format!(
            "Failed to parse node config at {}: {}",
            config_tree_path.display(),
            e
        ))
    })
}

#[derive(Clone)]
pub(crate) struct NodeAddActionContext {
    pub(crate) node_stack: Arc<NodeStack>,
    pub(crate) messenger: MessengerHandle,
    pub(crate) bound_core_node: String,
    pub(crate) core_instance_id: String,
    pub(crate) peppy_dirs: PeppyDirs,
}

struct ProcessNodeAddContext {
    action: NodeAddActionContext,
    feedback_tx: mpsc::UnboundedSender<FeedbackLine>,
    log_file: Arc<StdMutex<File>>,
    log_path: PathBuf,
}

async fn resolve_git_source(
    repo_url: &gix_url::Url,
    repo_path: &str,
    repo_ref: Option<&str>,
    feedback_tx: mpsc::UnboundedSender<FeedbackLine>,
) -> std::result::Result<ResolvedNodeAddSource, String> {
    let repo_relative_path = sanitize_repo_path(repo_path)?;

    let repo_url_bstring = repo_url.to_bstring();
    let repo_url_str = std::str::from_utf8(repo_url_bstring.as_ref())
        .map_err(|_| "repo_url must be valid UTF-8".to_string())?
        .to_owned();

    // --- Phase 1: Shallow probe — validate peppy.json5 without a full clone ---
    let _ = feedback_tx.send(FeedbackLine {
        stream: FeedbackStream::Stdout,
        line: "Checking node config...".to_string(),
    });

    let probe_url = repo_url_str.clone();
    let probe_path = repo_relative_path.clone();
    let probe_ref = repo_ref.map(str::to_owned);

    let phase1_result = tokio::task::spawn_blocking(move || {
        shallow_validate_config(&probe_url, &probe_path, probe_ref.as_deref())
    })
    .await
    .map_err(|e| format!("Failed to join shallow probe task: {}", e))?;

    let validated_config: Option<ParsedNodeConfig> = match phase1_result {
        Ok(config) => Some(config),
        Err(ShallowCheckError::InvalidConfig(msg)) => return Err(msg),
        Err(ShallowCheckError::ShallowFetchFailed(reason)) => {
            let _ = feedback_tx.send(FeedbackLine {
                stream: FeedbackStream::Stdout,
                line: format!(
                    "Shallow probe unavailable ({}), proceeding with full clone",
                    reason
                ),
            });
            None
        }
    };

    // --- Phase 2: Full clone (only reached if config is valid or probe fell back) ---
    let checkout_dir = tempfile::tempdir()
        .map_err(|e| format!("Failed to create temporary directory: {}", e))?
        .keep();

    let clone_checkout_dir = checkout_dir.clone();
    let clone_repo_url = repo_url_str.clone();
    let clone_repo_ref = repo_ref.map(str::to_owned);
    if let Err(err) = tokio::task::spawn_blocking(move || {
        let mut last_report = Instant::now();
        let mut callbacks = git2::RemoteCallbacks::new();
        callbacks.transfer_progress(move |progress| {
            if last_report.elapsed() >= Duration::from_millis(500) {
                last_report = Instant::now();
                let received = progress.received_objects();
                let total = progress.total_objects();
                let bytes = progress.received_bytes();
                let _ = feedback_tx.send(FeedbackLine {
                    stream: FeedbackStream::Stdout,
                    line: format!(
                        "Cloning: received {}/{} objects ({})",
                        received,
                        total,
                        format_bytes(bytes),
                    ),
                });
            }
            true
        });

        let mut fetch_opts = git2::FetchOptions::new();
        fetch_opts.remote_callbacks(callbacks);

        let repo = RepoBuilder::new()
            .fetch_options(fetch_opts)
            .clone(&clone_repo_url, &clone_checkout_dir)
            .map_err(|e| format!("Failed to clone repository: {}", e))?;
        if let Some(repo_ref) = clone_repo_ref.as_deref() {
            checkout_repo_ref(&repo, repo_ref)
                .map_err(|e| format!("Failed to checkout git ref '{}': {}", repo_ref, e))?;
        }
        Ok::<_, String>(())
    })
    .await
    .map_err(|e| format!("Failed to join git clone task: {}", e))?
    {
        std::fs::remove_dir_all(&checkout_dir).ok();
        return Err(err);
    }

    let candidate_path = checkout_dir.join(&repo_relative_path);

    let config_path = if candidate_path
        .extension()
        .and_then(|ext| ext.to_str())
        .is_some_and(|ext| ext.eq_ignore_ascii_case("json5"))
    {
        candidate_path
    } else {
        candidate_path.join(NODE_CONFIG_FILE)
    };

    let node_root_dir = config_path
        .parent()
        .map(PathBuf::from)
        .ok_or_else(|| "Invalid repo_path: node config has no parent directory".to_string())?;

    // Reuse the config from Phase 1 if available; otherwise parse from disk (fallback path).
    let node_config = if let Some(config) = validated_config {
        config
    } else {
        match NodeConfigParser::from_path(&config_path) {
            Ok(cfg) => cfg,
            Err(e) => {
                std::fs::remove_dir_all(&checkout_dir).ok();
                return Err(format!(
                    "Failed to parse node config at {}: {}",
                    config_path.display(),
                    e
                ));
            }
        }
    };

    Ok(ResolvedNodeAddSource {
        source_path: node_root_dir,
        node_config,
        cleanup_dir: Some(checkout_dir),
    })
}

fn format_bytes(bytes: usize) -> String {
    const KB: f64 = 1024.0;
    const MB: f64 = 1024.0 * 1024.0;
    let b = bytes as f64;
    if b >= MB {
        format!("{:.1} MB", b / MB)
    } else if b >= KB {
        format!("{:.0} KB", b / KB)
    } else {
        format!("{} B", bytes)
    }
}

fn sanitize_http_filename(name: &str) -> String {
    let sanitized: String = name
        .chars()
        .map(|ch| match ch {
            'a'..='z' | 'A'..='Z' | '0'..='9' | '.' | '-' | '_' => ch,
            _ => '_',
        })
        .collect();
    let sanitized = sanitized.trim_matches('_');
    if sanitized.is_empty() {
        "bundle.tar.zst".to_string()
    } else {
        sanitized.to_string()
    }
}

fn bundle_file_name(url: &url::Url) -> String {
    url.path_segments()
        .and_then(|mut segments| segments.next_back())
        .filter(|segment| !segment.is_empty())
        .map(sanitize_http_filename)
        .unwrap_or_else(|| "bundle.tar.zst".to_string())
}

fn download_http_bundle(
    url: &url::Url,
    destination: &Path,
    expected_sha256: Option<&str>,
    feedback_tx: Option<&mpsc::UnboundedSender<FeedbackLine>>,
) -> std::result::Result<(), String> {
    use sha2::{Digest, Sha256};

    let expected_bytes = expected_sha256
        .map(|hex| decode_sha256_hex(hex).map_err(|e| format!("Invalid SHA256 for {}: {}", url, e)))
        .transpose()?;

    let response = ureq::get(url.as_str()).call().map_err(|err| {
        let reason = match err {
            HttpError::StatusCode(code) => format!("unexpected status code {code}"),
            other => other.to_string(),
        };
        format!("Failed to download bundle from {}: {}", url, reason)
    })?;

    let total_size: Option<u64> = response
        .headers()
        .get("content-length")
        .and_then(|v| v.to_str().ok())
        .and_then(|s| s.parse().ok());

    let mut reader = response.into_body().into_reader();
    let mut file = File::create(destination).map_err(|e| {
        format!(
            "Failed to create bundle file {}: {}",
            destination.display(),
            e
        )
    })?;

    let mut hasher = expected_bytes.as_ref().map(|_| Sha256::new());
    let mut buffer = [0u8; 8 * 1024];
    let mut bytes_downloaded: u64 = 0;
    let mut last_report = Instant::now();
    loop {
        let read = reader
            .read(&mut buffer)
            .map_err(|e| format!("Failed to read response body from {}: {}", url, e))?;
        if read == 0 {
            break;
        }
        bytes_downloaded += read as u64;
        file.write_all(&buffer[..read]).map_err(|e| {
            format!(
                "Failed to write bundle file {}: {}",
                destination.display(),
                e
            )
        })?;
        if let Some(ref mut h) = hasher {
            h.update(&buffer[..read]);
        }
        if let Some(tx) = feedback_tx
            && last_report.elapsed() >= Duration::from_millis(500)
        {
            last_report = Instant::now();
            let progress_msg = if let Some(total) = total_size {
                let pct = if total > 0 {
                    (bytes_downloaded as f64 / total as f64 * 100.0) as u64
                } else {
                    0
                };
                format!(
                    "Downloading: {} / {} ({}%)",
                    format_bytes(bytes_downloaded as usize),
                    format_bytes(total as usize),
                    pct,
                )
            } else {
                format!("Downloading: {}", format_bytes(bytes_downloaded as usize))
            };
            let _ = tx.send(FeedbackLine {
                stream: FeedbackStream::Stdout,
                line: progress_msg,
            });
        }
    }
    file.flush().map_err(|e| {
        format!(
            "Failed to flush bundle file {}: {}",
            destination.display(),
            e
        )
    })?;

    if let Some((hasher, expected)) = hasher.zip(expected_bytes) {
        let computed = hasher.finalize();
        if computed.as_slice() != expected.as_slice() {
            std::fs::remove_file(destination).ok();
            return Err(format!(
                "SHA256 checksum mismatch for {}: expected {}, computed {}",
                url,
                expected_sha256.unwrap_or_default(),
                encode_hex(computed.as_slice()),
            ));
        }
    }

    Ok(())
}

fn decode_sha256_hex(input: &str) -> std::result::Result<Vec<u8>, String> {
    let bytes = input.as_bytes();
    if bytes.len() != 64 {
        return Err(format!("expected 64 hex characters, got {}", bytes.len()));
    }
    // Input is already validated as lowercase hex by config parsing (source.rs),
    // so we can convert directly without error handling per digit.
    let mut output = Vec::with_capacity(32);
    for chunk in bytes.chunks_exact(2) {
        let high = (chunk[0] as char).to_digit(16).unwrap() as u8;
        let low = (chunk[1] as char).to_digit(16).unwrap() as u8;
        output.push((high << 4) | low);
    }
    Ok(output)
}

fn encode_hex(bytes: &[u8]) -> String {
    bytes.iter().map(|b| format!("{:02x}", b)).collect()
}

fn extract_http_bundle(
    bundle_path: &Path,
    destination: &Path,
    url: &url::Url,
) -> std::result::Result<(), String> {
    extract_tar_zst(bundle_path, destination).map_err(|e| format!("{} (source: {})", e, url))
}

pub(crate) async fn download_and_extract_http_source(
    url: &url::Url,
    peppy_dirs: PeppyDirs,
    expected_sha256: Option<String>,
) -> std::result::Result<ExtractedHttpSource, String> {
    let url = url.clone();
    tokio::task::spawn_blocking(move || {
        download_and_extract_http_source_blocking(url, &peppy_dirs, expected_sha256)
    })
    .await
    .map_err(|e| format!("Failed to join HTTP download task: {}", e))?
}

pub(crate) async fn resolve_http_source(
    url: &url::Url,
    peppy_dirs: PeppyDirs,
    expected_sha256: Option<String>,
) -> std::result::Result<ResolvedNodeAddSource, String> {
    let url = url.clone();
    tokio::task::spawn_blocking(move || {
        resolve_http_source_blocking(url, &peppy_dirs, expected_sha256, None)
    })
    .await
    .map_err(|e| format!("Failed to join HTTP download task: {}", e))?
}

async fn resolve_http_source_with_feedback(
    url: &url::Url,
    peppy_dirs: PeppyDirs,
    expected_sha256: Option<String>,
    feedback_tx: mpsc::UnboundedSender<FeedbackLine>,
) -> std::result::Result<ResolvedNodeAddSource, String> {
    let url = url.clone();
    tokio::task::spawn_blocking(move || {
        resolve_http_source_blocking(url, &peppy_dirs, expected_sha256, Some(&feedback_tx))
    })
    .await
    .map_err(|e| format!("Failed to join HTTP download task: {}", e))?
}

fn download_and_extract_http_source_blocking(
    url: url::Url,
    peppy_dirs: &PeppyDirs,
    expected_sha256: Option<String>,
) -> std::result::Result<ExtractedHttpSource, String> {
    match url.scheme() {
        "http" | "https" => {}
        other => {
            return Err(format!(
                "HTTP source URL must use http or https (got scheme '{}')",
                other
            ));
        }
    }

    if !is_supported_http_archive(&url) {
        return Err(
            "Only tar.zst (.tar.zstd/.tar.zst/.tzst) archives are supported for HTTP sources"
                .to_string(),
        );
    }

    let http_base_dir = peppy_dirs.http_downloads_dir();
    std::fs::create_dir_all(&http_base_dir)
        .map_err(|e| format!("Failed to create HTTP download directory: {}", e))?;

    let timestamp = Local::now().format("%Y%m%d_%H%M%S_%3f");
    let operation_dir =
        http_base_dir.join(format!("node_add_{timestamp}_{}", generate_random_id()));
    std::fs::create_dir_all(&operation_dir)
        .map_err(|e| format!("Failed to create HTTP staging directory: {}", e))?;

    let mut operation_cleanup = CleanupDir::new(Some(operation_dir.clone()));

    let bundle_path = operation_dir.join(bundle_file_name(&url));
    let extract_dir = operation_dir.join("extracted");
    std::fs::create_dir_all(&extract_dir)
        .map_err(|e| format!("Failed to create bundle extract directory: {}", e))?;

    download_http_bundle(&url, &bundle_path, expected_sha256.as_deref(), None)?;
    extract_http_bundle(&bundle_path, &extract_dir, &url)?;
    std::fs::remove_file(&bundle_path).ok();

    let node_root_dir = locate_node_root_dir(&extract_dir)?;

    let operation_dir = operation_cleanup.take();

    Ok(ExtractedHttpSource {
        source_path: node_root_dir,
        cleanup_dir: operation_dir,
    })
}

fn resolve_http_source_download_and_extract(
    url: url::Url,
    peppy_dirs: &PeppyDirs,
    expected_sha256: Option<String>,
    feedback_tx: Option<&mpsc::UnboundedSender<FeedbackLine>>,
) -> std::result::Result<ExtractedHttpSource, String> {
    match url.scheme() {
        "http" | "https" => {}
        other => {
            return Err(format!(
                "HTTP source URL must use http or https (got scheme '{}')",
                other
            ));
        }
    }

    if !is_supported_http_archive(&url) {
        return Err(
            "Only tar.zst (.tar.zstd/.tar.zst/.tzst) archives are supported for HTTP sources"
                .to_string(),
        );
    }

    let http_base_dir = peppy_dirs.http_downloads_dir();
    std::fs::create_dir_all(&http_base_dir)
        .map_err(|e| format!("Failed to create HTTP download directory: {}", e))?;

    let timestamp = Local::now().format("%Y%m%d_%H%M%S_%3f");
    let operation_dir =
        http_base_dir.join(format!("node_add_{timestamp}_{}", generate_random_id()));
    std::fs::create_dir_all(&operation_dir)
        .map_err(|e| format!("Failed to create HTTP staging directory: {}", e))?;

    let mut operation_cleanup = CleanupDir::new(Some(operation_dir.clone()));

    let bundle_path = operation_dir.join(bundle_file_name(&url));
    let extract_dir = operation_dir.join("extracted");
    std::fs::create_dir_all(&extract_dir)
        .map_err(|e| format!("Failed to create bundle extract directory: {}", e))?;

    download_http_bundle(&url, &bundle_path, expected_sha256.as_deref(), feedback_tx)?;
    extract_http_bundle(&bundle_path, &extract_dir, &url)?;
    std::fs::remove_file(&bundle_path).ok();

    let node_root_dir = locate_node_root_dir(&extract_dir)?;

    let operation_dir = operation_cleanup.take();

    Ok(ExtractedHttpSource {
        source_path: node_root_dir,
        cleanup_dir: operation_dir,
    })
}

fn resolve_http_source_blocking(
    url: url::Url,
    peppy_dirs: &PeppyDirs,
    expected_sha256: Option<String>,
    feedback_tx: Option<&mpsc::UnboundedSender<FeedbackLine>>,
) -> std::result::Result<ResolvedNodeAddSource, String> {
    let extracted =
        resolve_http_source_download_and_extract(url, peppy_dirs, expected_sha256, feedback_tx)?;
    let config_path = extracted.source_path.join(NODE_CONFIG_FILE);
    let node_config = NodeConfigParser::from_path(&config_path).map_err(|e| {
        format!(
            "Failed to parse node config at {}: {}",
            config_path.display(),
            e
        )
    })?;

    Ok(ResolvedNodeAddSource {
        source_path: extracted.source_path,
        node_config,
        cleanup_dir: extracted.cleanup_dir,
    })
}

/// Derives a label for the log filename from the NodeSource without network I/O.
/// For Fs sources, reads the local config to get `{name}_{tag}` (fast, local I/O only).
/// For Git/Http sources, returns a UUID since the node name/tag are unknown before cloning.
pub(crate) fn log_label_from_source(source: &NodeSource) -> String {
    match source {
        NodeSource::Fs(path) => {
            if is_supported_fs_archive(path)
                && let Ok(resolved) = resolve_local_archive_source(path)
            {
                let label = format!(
                    "{}_{}",
                    resolved.node_config.manifest_name(),
                    resolved.node_config.manifest_tag()
                );
                return label;
            }

            let config_path = path.join(NODE_CONFIG_FILE);
            if let Ok(config) = NodeConfigParser::from_path(&config_path) {
                return format!("{}_{}", config.manifest_name(), config.manifest_tag());
            }
            path.file_name()
                .and_then(|n| n.to_str())
                .unwrap_or("unknown")
                .to_string()
        }
        NodeSource::Git { .. } | NodeSource::Http { .. } => generate_random_id(),
    }
}

async fn resolve_node_add_source(
    goal: &NodeAddGoal,
    peppy_dirs: &PeppyDirs,
    feedback_tx: &mpsc::UnboundedSender<FeedbackLine>,
) -> std::result::Result<ResolvedNodeAddSource, String> {
    match &goal.source {
        NodeSource::Fs(path) => {
            // When using the stack-launch marker, skip git hash verification and fingerprint
            // checks. This allows stack_launch to work with local filesystem sources without
            // requiring `peppy node sync` beforehand - fresh peppygen will be generated.
            let is_stack_launch = goal.git_hash == STACK_LAUNCH_GIT_HASH;

            if is_supported_fs_archive(path) {
                let resolved = resolve_local_archive_source(path)?;
                if !is_stack_launch {
                    verify_git_hash(&resolved.source_path, &goal.git_hash)?;
                }
                return Ok(ResolvedNodeAddSource {
                    source_path: resolved.source_path,
                    node_config: resolved.node_config,
                    cleanup_dir: Some(resolved.temp_dir.keep()),
                });
            }

            // Git hash verification is deferred to run_node_add (after variant
            // resolution) so that the check uses the final source_path — which
            // may be a variant subdirectory that has no .peppy at the root level.
            let config_path = path.join(NODE_CONFIG_FILE);
            let node_config = NodeConfigParser::from_path(&config_path).map_err(|e| {
                format!(
                    "Failed to parse node config at {}: {}",
                    config_path.display(),
                    e
                )
            })?;
            Ok(ResolvedNodeAddSource {
                source_path: path.clone(),
                node_config,
                cleanup_dir: None,
            })
        }
        NodeSource::Git {
            repo_url,
            repo_path,
            repo_ref,
        } => {
            let _ = feedback_tx.send(FeedbackLine {
                stream: FeedbackStream::Stdout,
                line: format!("Cloning repository {}...", repo_url.to_bstring()),
            });
            resolve_git_source(
                repo_url,
                repo_path,
                repo_ref.as_deref(),
                feedback_tx.clone(),
            )
            .await
        }
        NodeSource::Http { url, sha256 } => {
            let _ = feedback_tx.send(FeedbackLine {
                stream: FeedbackStream::Stdout,
                line: format!("Downloading bundle from {}...", url),
            });
            resolve_http_source_with_feedback(
                url,
                peppy_dirs.clone(),
                sha256.clone(),
                feedback_tx.clone(),
            )
            .await
        }
    }
}

use super::variant::{resolve_variant, variant_label};

/// Encodes a rejected goal response, mapping encoding errors to `PeppyError`.
fn encode_rejected_goal(reason: impl Into<String>) -> PeppyResult<Payload> {
    NodeAddGoalResponse::rejected(reason).encode().map_err(|e| {
        peppylib::PeppyError::InvalidServiceRequest {
            identifier: "node_add_goal".to_string(),
            reason: format!("Failed to encode response: {}", e),
        }
    })
}

/// Runs the full node-add pipeline: resolves the source, renames the log file
/// to its canonical form, calls [`process_node_add`], and catches panics.
///
/// The caller is responsible for creating the log file (so the action-server
/// path can include its path in the goal response before spawning this).
///
/// This is the shared implementation used by both the action-server path
/// ([`handle_goal_request`]) and the direct-call path from `stack_launch`.
pub(crate) async fn run_node_add(
    goal: NodeAddGoal,
    action_context: NodeAddActionContext,
    feedback_tx: mpsc::UnboundedSender<FeedbackLine>,
    log_file: Arc<StdMutex<File>>,
    log_path: PathBuf,
    timestamp: String,
) -> NodeAddResult {
    let log_dir = action_context.peppy_dirs.logs_dir_add();

    let log_file_for_panic = log_file.clone();
    let log_path_for_panic = log_path.clone();

    match AssertUnwindSafe(async {
        // Resolve source (git clone, HTTP download, or local config check).
        let mut resolved = match resolve_node_add_source(&goal, &action_context.peppy_dirs, &feedback_tx).await {
            Ok(r) => r,
            Err(error_msg) => {
                write_error_to_log(&log_file, &error_msg);
                return NodeAddResult::failure(&log_path, error_msg);
            }
        };

        // RAII guard: ensures resolved.cleanup_dir is removed on any early return
        // (e.g. variant resolution failure) before process_node_add takes ownership.
        let mut resolved_cleanup_guard = CleanupDir::new(resolved.cleanup_dir.take());

        // Auto-resolve the default variant when no explicit variant is specified.
        let effective_variant = match &goal.variant {
            Some(v) => Some(v.clone()),
            None if resolved.node_config.has_default_variant() => {
                Some(NodeSource::Fs(DEFAULT_VARIANT_NAME.into()))
            }
            None => None,
        };

        // Capture the root source path before variant resolution may overwrite it.
        // The .peppy/git.hash file is written by `peppy node sync` at the root
        // level; non-local variant directories (Git/Http clones) won't have it.
        let root_source_path = resolved.source_path.clone();
        let root_execution_language = resolved.node_config.execution_language();

        // If a variant is specified (or auto-resolved), resolve it from the root config.
        let mut variant_cleanup_dir: Option<PathBuf> = None;
        let mut variant_source_is_local = true;
        let node_config: NodeConfig;
        if let Some(ref variant_source) = effective_variant {
            let label = variant_label(variant_source);
            match resolve_variant(
                variant_source,
                &resolved.node_config,
                &resolved.source_path,
                &action_context.peppy_dirs,
                None,
            )
            .await
            {
                Ok(v) => {
                    if v.manifest_ignored {
                        let _ = feedback_tx.send(FeedbackLine {
                            stream: FeedbackStream::Stderr,
                            line: format!(
                                "Warning: variant '{}' defines a `manifest` section which will be ignored — only the root node's manifest is used",
                                label
                            ),
                        });
                    }
                    node_config = v.merged_config;
                    resolved.source_path = v.variant_source_path;
                    variant_source_is_local = v.source_is_local;
                    variant_cleanup_dir = v.cleanup_dir;
                }
                Err(error_msg) => {
                    write_error_to_log(&log_file, &error_msg);
                    return NodeAddResult::failure(&log_path, error_msg);
                }
            }
        } else {
            match resolved.node_config.into_resolved() {
                Ok(cfg) => node_config = cfg,
                Err(e) => {
                    let error_msg = e.to_string();
                    write_error_to_log(&log_file, &error_msg);
                    return NodeAddResult::failure(&log_path, error_msg);
                }
            }
        }

        // Auto-generate .peppy directory if missing (e.g. fresh clone never synced).
        // Must run before git hash verification since sync also writes git.hash.
        //
        // Generation and filesystem I/O are blocking; offload to spawn_blocking
        // to avoid stalling the Tokio runtime (mirrors the daemon node-sync path).
        if goal.git_hash != STACK_LAUNCH_GIT_HASH
            && let NodeSource::Fs(original_path) = &goal.source
            && !is_supported_fs_archive(original_path)
        {
            let sync_node_dir = root_source_path.clone();
            let sync_execution_language = root_execution_language;
            let sync_manifest = node_config.manifest.clone();
            let sync_interfaces = node_config.interfaces.clone();
            let sync_git_hash = goal.git_hash.clone();
            let sync_node_stack = action_context.node_stack.clone();
            let sync_peppy_dirs = action_context.peppy_dirs.clone();

            let sync_variant = if variant_source_is_local
                && effective_variant.is_some()
                && resolved.source_path != root_source_path
            {
                Some((
                    resolved.source_path.clone(),
                    node_config.execution.language,
                    node_config.clone(),
                ))
            } else {
                None
            };

            let sync_result = tokio::task::spawn_blocking(move || {
                let variant = sync_variant.as_ref().map(|(dir, language, cfg)| {
                    AutoSyncVariant {
                        dir,
                        language: *language,
                        merged_config: cfg,
                    }
                });

                sync::auto_sync_if_missing(
                    AutoSyncParams {
                        node_dir: &sync_node_dir,
                        execution_language: sync_execution_language,
                        manifest: &sync_manifest,
                        interfaces: &sync_interfaces,
                        git_hash: &sync_git_hash,
                        variant,
                    },
                    &sync_node_stack,
                    &sync_peppy_dirs,
                )
            })
            .await;

            match sync_result {
                Ok(Ok(())) => {}
                Ok(Err(e)) => {
                    let msg = format!("Auto-sync failed: {}", e);
                    write_error_to_log(&log_file, &msg);
                    return NodeAddResult::failure(&log_path, msg);
                }
                Err(e) => {
                    let msg = format!("Auto-sync task failed: {}", e);
                    write_error_to_log(&log_file, &msg);
                    return NodeAddResult::failure(&log_path, msg);
                }
            }
        }

        // Verify git hash for non-archive local FS sources.
        //
        // The .peppy/git.hash file is always written by `peppy node sync` at
        // the root level (alongside the peppy.json5 that contains the manifest),
        // regardless of whether the node has an execution block or uses variants.
        // Verification always targets the root source path.
        if goal.git_hash != STACK_LAUNCH_GIT_HASH
            && let NodeSource::Fs(original_path) = &goal.source
            && !is_supported_fs_archive(original_path)
            && let Err(error_msg) = verify_git_hash(&root_source_path, &goal.git_hash)
        {
            write_error_to_log(&log_file, &error_msg);
            return NodeAddResult::failure(&log_path, error_msg);
        }

        let cleanup_dir = resolved_cleanup_guard.take();
        let source_path = resolved.source_path.clone();

        // Fingerprints are only generated locally by `peppy node sync`.
        // Git/Http sources never have them, so skip verification for remote sources.
        let is_local_root =
            matches!(&goal.source, NodeSource::Fs(_)) && goal.git_hash != STACK_LAUNCH_GIT_HASH;
        let verify_codegen_fingerprint = is_local_root && variant_source_is_local;

        // Rename log file to the canonical {name}_{tag}_{timestamp}.log format
        // now that we know the node name and tag from the resolved config.
        let node_name = node_config.manifest.name.as_str();
        let node_tag = &node_config.manifest.tag;
        let canonical_filename = format!("{}_{}_{}.log", node_name, node_tag, timestamp);
        let canonical_log_path = log_dir.join(&canonical_filename);
        let log_path = if std::fs::rename(&log_path, &canonical_log_path).is_ok() {
            canonical_log_path
        } else {
            log_path
        };

        // RAII guard: cleans up variant clone/download dir on any exit path.
        let _variant_cleanup_guard = CleanupDir::new(variant_cleanup_dir);

        let ctx = ProcessNodeAddContext {
            action: action_context,
            feedback_tx,
            log_file,
            log_path,
        };
        process_node_add(
            goal,
            node_config,
            source_path,
            verify_codegen_fingerprint,
            cleanup_dir,
            ctx,
        )
        .await
    })
    .catch_unwind()
    .await
    {
        Ok(result) => result,
        Err(panic_payload) => {
            let msg = format!(
                "node_add task panicked: {}",
                super::panic_message(&*panic_payload)
            );
            tracing::error!("{}", msg);
            write_error_to_log(&log_file_for_panic, &msg);
            NodeAddResult::failure(log_path_for_panic, msg)
        }
    }
}

async fn handle_goal_request(
    context: ServiceRequestContext,
    feedback_publisher: TopicPublisher,
    state: Arc<Mutex<ActionState<NodeAddResult>>>,
    action_context: NodeAddActionContext,
    running_since: Arc<Mutex<Option<(Instant, u64)>>>,
    running_task: Arc<Mutex<Option<JoinHandle<()>>>>,
) -> PeppyResult<Payload> {
    let sender_instance_id = context.message().instance_id();
    let payload = context.message().payload();

    let goal = match NodeAddGoal::decode(payload.as_ref()) {
        Ok(g) => g,
        Err(e) => return encode_rejected_goal(format!("invalid payload: {}", e)),
    };

    // Check if already running and mark as running if not
    {
        let mut state_guard = state.lock().await;
        if matches!(*state_guard, ActionState::Running) {
            if !goal.force {
                let running_guard = running_since.lock().await;
                let remaining = running_guard
                    .map(|(started_at, timeout_secs)| {
                        Duration::from_secs(timeout_secs)
                            .saturating_sub(started_at.elapsed())
                            .as_secs()
                    })
                    .unwrap_or(0);
                return encode_rejected_goal(format!(
                    "action already in progress (times out in {remaining}s), \
                     use `--force` to force adding the node"
                ));
            }

            // Force mode: abort the old task and reset state
            debug!("Force flag set: aborting previous node_add task");
            let mut task_guard = running_task.lock().await;
            if let Some(handle) = task_guard.take() {
                handle.abort();
            }
        }
        *state_guard = ActionState::Running;
        *running_since.lock().await = Some((Instant::now(), goal.timeout_secs));
    }

    match &goal.source {
        NodeSource::Fs(path) => debug!(
            "Received `node_add` goal from {sender_instance_id}, source={}",
            path.display()
        ),
        NodeSource::Git {
            repo_url,
            repo_path,
            repo_ref,
        } => debug!(
            "Received `node_add` goal from {sender_instance_id}, source=git:{}::{} ({:?})",
            repo_url, repo_path, repo_ref
        ),
        NodeSource::Http { url, .. } => debug!(
            "Received `node_add` goal from {sender_instance_id}, source=http:{}",
            url
        ),
    }

    // Create the log file *before* source resolution so that clone/download
    // progress and any errors are captured in the log from the very start.
    let log_label = log_label_from_source(&goal.source);
    let log_dir = action_context.peppy_dirs.logs_dir_add();
    let timestamp = Local::now().format("%Y%m%d_%H%M%S_%3f").to_string();
    let log_filename = format!("{}_{}.log", log_label, timestamp);
    let (log_file, log_path) = match create_action_log_file(&log_dir, &log_filename) {
        Ok(result) => result,
        Err(error_msg) => {
            debug!("{}", error_msg);
            let mut state_guard = state.lock().await;
            *state_guard = ActionState::Rejected;
            return encode_rejected_goal(error_msg);
        }
    };

    debug!("Created log file for node add: {}", log_path.display());

    // Process the add operation in a separate task to not block goal response.
    let state_clone = Arc::clone(&state);
    let log_path_clone = log_path.clone();
    let task_handle = tokio::spawn(async move {
        // Create a channel for feedback and spawn a consumer that encodes
        // FeedbackLine values as NodeAddFeedback and publishes to the topic.
        let (feedback_tx, mut feedback_rx) = mpsc::unbounded_channel::<FeedbackLine>();
        let feedback_publisher_for_consumer = feedback_publisher.clone();
        let consumer_handle = tokio::spawn(async move {
            while let Some(line) = feedback_rx.recv().await {
                let feedback = match line.stream {
                    FeedbackStream::Stdout => NodeAddFeedback::stdout(&line.line),
                    FeedbackStream::Stderr => NodeAddFeedback::stderr(&line.line),
                };
                if let Ok(payload) = feedback.encode() {
                    let _ = feedback_publisher_for_consumer.publish(payload).await;
                }
            }
        });

        let result = run_node_add(
            goal,
            action_context,
            feedback_tx,
            log_file,
            log_path_clone,
            timestamp,
        )
        .await;

        // Wait for the feedback consumer to drain before completing.
        let _ = consumer_handle.await;
        let mut state_guard = state_clone.lock().await;
        *state_guard = ActionState::Completed { result };
    });

    // Store the handle so a future --force call can abort this task.
    *running_task.lock().await = Some(task_handle);

    let response = NodeAddGoalResponse::accepted(&log_path);
    response
        .encode()
        .map_err(|e| peppylib::PeppyError::InvalidServiceRequest {
            identifier: "node_add_goal".to_string(),
            reason: format!("Failed to encode response: {}", e),
        })
}

async fn shutdown_existing_instances(
    node_name: &str,
    node_tag: &str,
    ctx: &ProcessNodeAddContext,
) -> std::result::Result<(), String> {
    let Some(entity) = ctx.action.node_stack.find(node_name, node_tag) else {
        return Ok(());
    };

    let instances = {
        let guard = entity.read().expect("entity poisoned");
        if guard.instances().is_empty() {
            return Ok(());
        }
        guard
            .instances()
            .iter()
            .map(|instance| instance.instance_id().clone())
            .collect::<Vec<_>>()
    };

    for instance_id in instances {
        let instance_id_str = instance_id.as_str().to_owned();
        debug!(
            "Shutting down existing node instance {}, node={}:{}",
            instance_id_str, node_name, node_tag
        );

        super::stop::stop_instance(
            &ctx.action.messenger,
            &ctx.action.bound_core_node,
            &ctx.action.core_instance_id,
            &ctx.action.node_stack,
            node_name,
            node_tag,
            &instance_id,
        )
        .await?;

        let _ = ctx.feedback_tx.send(FeedbackLine {
            stream: FeedbackStream::Stdout,
            line: format!("{instance_id_str} has been stopped"),
        });
    }

    Ok(())
}

async fn process_node_add(
    goal: NodeAddGoal,
    node_config: NodeConfig,
    source_path: PathBuf,
    verify_codegen_fingerprint: bool,
    cleanup_dir: Option<PathBuf>,
    ctx: ProcessNodeAddContext,
) -> NodeAddResult {
    let mut env_vars = match super::validate_goal_env_vars(&goal.env_vars) {
        Ok(vars) => vars,
        Err(e) => {
            let msg = e.to_string();
            write_error_to_log(&ctx.log_file, &msg);
            return NodeAddResult::failure(&ctx.log_path, msg);
        }
    };
    let node_name = node_config.manifest.name.as_str().to_owned();
    let node_tag = node_config.manifest.tag.clone();
    let sccache_injected =
        super::inject_rust_build_env(&mut env_vars, node_config.execution.language);
    if sccache_injected {
        let _ = ctx.feedback_tx.send(FeedbackLine {
            stream: FeedbackStream::Stdout,
            line: "Using sccache for Rust compilation".to_string(),
        });
    }
    super::inject_node_runtime_env(&mut env_vars, &node_name, &node_tag);
    let _cleanup_guard = CleanupDir::new(cleanup_dir);

    // Capture the previous .sif/archive path (if any) so we can clean it up
    // after the new entity is in place. Only nodes that have already reached
    // `Built` have an artifact_path.
    let previous_snapshot_path =
        ctx.action
            .node_stack
            .find(&node_name, &node_tag)
            .and_then(|entity| {
                entity
                    .read()
                    .expect("entity poisoned")
                    .artifact_path()
                    .map(|p| p.to_path_buf())
            });

    if verify_codegen_fingerprint {
        // Verify that the node config fingerprint matches the one in the generated folder.
        // Even if the `.peppy` content will be regenerated in the copy, we want to make sure the code that
        // the user has written for their node matches the current interface version.
        let config_path = source_path.join(NODE_CONFIG_FILE);
        if let Err(e) =
            config::fingerprint::verify_codegen_fingerprint(&config_path, PEPPYGEN_OUTPUT_PATH)
        {
            let msg = format!("Codegen fingerprint verification failed: {}", e);
            write_error_to_log(&ctx.log_file, &msg);
            return NodeAddResult::failure(&ctx.log_path, msg);
        }
    }

    // Copy the node folder to a temporary working directory.
    let (working_dir, excluded_dirs) =
        match copy_node_to_temp_dir(&source_path, &ctx.action.peppy_dirs.tmp_dir()) {
            Ok(result) => result,
            Err(e) => {
                let msg = format!("Failed to copy node folder: {}", e);
                write_error_to_log(&ctx.log_file, &msg);
                return NodeAddResult::failure(&ctx.log_path, msg);
            }
        };
    // RAII guard: cleans up the temp working dir on any exit path.
    let working_dir_cleanup = CleanupDir::new(Some(working_dir.clone()));

    // For variant adds (including auto-resolved default variants), write the
    // merged config (root manifest + interfaces + variant execution) into the
    // working directory so the peppygen generator finds a valid NodeConfig.
    // Strip the variants list from the manifest — it is no longer relevant
    // once the variant has been resolved and would trigger a validation error
    // if a "default" variant is present alongside an execution.
    if goal.variant.is_some() || node_config.manifest.has_default_variant() {
        let mut write_config = node_config.clone();
        write_config.manifest.variants = None;
        let merged_config_str = serde_json5::to_string(&write_config)
            .map_err(|e| format!("Failed to serialize merged variant config: {}", e));
        match merged_config_str {
            Ok(content) => {
                let config_path = working_dir.join(NODE_CONFIG_FILE);
                if let Err(e) = std::fs::write(&config_path, &content) {
                    let msg = format!("Failed to write merged variant config: {}", e);
                    write_error_to_log(&ctx.log_file, &msg);
                    return NodeAddResult::failure(&ctx.log_path, msg);
                }
                // Regenerate fingerprint for the new config
                if let Err(e) = config::fingerprint::generate_node_config_fingerprint(
                    &config_path,
                    working_dir.join(PEPPYGEN_OUTPUT_PATH),
                ) {
                    let msg = format!(
                        "Failed to regenerate fingerprint for merged variant config: {}",
                        e
                    );
                    write_error_to_log(&ctx.log_file, &msg);
                    return NodeAddResult::failure(&ctx.log_path, msg);
                }
            }
            Err(msg) => {
                write_error_to_log(&ctx.log_file, &msg);
                return NodeAddResult::failure(&ctx.log_path, msg);
            }
        }
    }

    if !excluded_dirs.is_empty() {
        let _ = ctx.feedback_tx.send(FeedbackLine {
            stream: FeedbackStream::Stdout,
            line: format!(
                "Excluded directories from copy: {}",
                excluded_dirs.join(", ")
            ),
        });
    }

    // Validate that all dependency nodes exist in the stack and expose the required
    // interfaces before running add_cmd. This prevents confusing build failures when
    // peppygen is generated with incomplete interfaces due to missing dependencies.
    let dep_errors = validate_dependency_specs(
        &node_config.manifest,
        &node_config.interfaces,
        &node_name,
        &node_tag,
        |name, tag| {
            ctx.action
                .node_stack
                .find(name, tag)
                .map(|e| e.read().expect("entity poisoned").config().clone())
        },
    );
    if let Some(err) = dep_errors.into_iter().next() {
        let msg = format!("Failed to add node config: {}", err);
        write_error_to_log(&ctx.log_file, &msg);
        return NodeAddResult::failure(&ctx.log_path, msg);
    }

    // Generate the peppygen library in the working directory.
    // Container builds need Copy mode because Apptainer's `%files` copies symlinks
    // as-is — absolute symlinks to the host cache would be broken inside the container.
    let language = node_config.execution.language;
    let deploy_mode = if node_config.execution.container.is_some() {
        generator::CrateDeployMode::Copy
    } else {
        generator::CrateDeployMode::Symlink
    };
    let consumed_interfaces = collect_consumed_interfaces(
        &node_config.manifest,
        &node_config.interfaces,
        &ctx.action.node_stack,
    );
    if let Err(e) = generate_peppygen_for_node(
        language,
        &working_dir,
        consumed_interfaces,
        &goal.git_hash,
        &ctx.action.peppy_dirs,
        deploy_mode,
        None,
    ) {
        let msg = format!("Failed to generate peppygen library: {}", e);
        write_error_to_log(&ctx.log_file, &msg);
        return NodeAddResult::failure(&ctx.log_path, msg);
    }

    // For process nodes, run the user-defined add_cmd in the working dir
    // before handing off to NodeEntity::build (which only does the
    // archive/sif step that immediately follows it).
    if node_config.execution.container.is_none() {
        let add_cmd = node_config.execution.add_cmd.as_ref();
        if let Err(e) = run_add_cmd_with_streaming(
            add_cmd,
            &working_dir,
            &env_vars,
            &ctx.feedback_tx,
            Arc::clone(&ctx.log_file),
        )
        .await
        {
            let msg = format!("add_cmd failed: {}", e);
            write_error_to_log(&ctx.log_file, &msg);
            return NodeAddResult::failure(&ctx.log_path, msg);
        }
    }

    // Stop any pre-existing instances of this node before resetting the
    // entity in the stack. push_config below replaces the entity wholesale
    // with a fresh `Added` one, so any tracked instances would otherwise be
    // forgotten without being shut down cleanly.
    if let Err(e) = shutdown_existing_instances(&node_name, &node_tag, &ctx).await {
        let msg = format!("Failed to shutdown existing node instances: {}", e);
        write_error_to_log(&ctx.log_file, &msg);
        return NodeAddResult::failure(&ctx.log_path, msg);
    }

    // Push the node config into the stack as an `Added` entity. The
    // config_path is the source `peppy.json5` (the user-owned location);
    // the entity will move to `Built` once NodeEntity::build runs.
    let config_path_for_stack = source_path.join(NODE_CONFIG_FILE);
    if let Err(e) =
        ctx.action
            .node_stack
            .push_config(node_config.clone(), false, &config_path_for_stack)
    {
        let msg = format!("Failed to add node config: {}", e);
        write_error_to_log(&ctx.log_file, &msg);
        return NodeAddResult::failure(&ctx.log_path, msg);
    }

    // Drive the build via the entity itself. This either runs apptainer
    // (container nodes) or archives `working_dir` (process nodes), and
    // transitions the entity from `Added` to `Built` with the resulting
    // `.sif`/archive path on success.
    let entity_handle = match ctx.action.node_stack.find(&node_name, &node_tag) {
        Some(handle) => handle,
        None => {
            let msg = format!(
                "internal error: just-pushed entity {}:{} disappeared from the stack",
                node_name, node_tag
            );
            write_error_to_log(&ctx.log_file, &msg);
            return NodeAddResult::failure(&ctx.log_path, msg);
        }
    };

    let build_result = node_stack::NodeEntity::build(
        &entity_handle,
        BuildContext {
            working_dir: &working_dir,
            peppy_dirs: &ctx.action.peppy_dirs,
            feedback_tx: &ctx.feedback_tx,
            log_file: Arc::clone(&ctx.log_file),
        },
    )
    .await;

    if let Err(e) = build_result {
        // Roll back the half-pushed entity so the stack doesn't keep an
        // `Added` placeholder for a node that never built successfully.
        // Only remove if the entity in the stack is still *our* `Added`
        // placeholder — if a competing add already replaced it (different
        // handle, or already advanced past `Added`), leave it alone so we
        // don't delete a newer winner.
        let still_ours = match ctx.action.node_stack.find(&node_name, &node_tag) {
            Some(current) if Arc::ptr_eq(&current, &entity_handle) => match current.read() {
                Ok(guard) => matches!(guard.stage(), node_stack::NodeStage::Added { .. }),
                Err(_) => false,
            },
            _ => false,
        };
        if still_ours {
            let _ = ctx.action.node_stack.remove_config(&node_name, &node_tag);
        }
        let msg = format!("Failed to build node: {}", e);
        write_error_to_log(&ctx.log_file, &msg);
        return NodeAddResult::failure(&ctx.log_path, msg);
    }

    // Re-read the entity to get the freshly recorded artifact_path for
    // cleanup and the success message.
    let snapshot_path = entity_handle
        .read()
        .expect("entity poisoned")
        .artifact_path()
        .expect("entity must have an artifact_path after a successful build")
        .to_path_buf();

    // Working dir is no longer needed; clean it up immediately.
    drop(working_dir_cleanup);

    // Clean up previous snapshot if it differs from the new one.
    if let Some(previous_snapshot_path) = previous_snapshot_path
        && previous_snapshot_path != snapshot_path
    {
        let storage_dir = ctx.action.peppy_dirs.added_nodes_dir();
        if previous_snapshot_path.starts_with(&storage_dir) {
            if previous_snapshot_path.is_dir() {
                std::fs::remove_dir_all(&previous_snapshot_path).ok();
            } else {
                std::fs::remove_file(&previous_snapshot_path).ok();
            }
        }
    }

    debug!(
        "Added node {}:{} at {}",
        node_name,
        node_tag,
        snapshot_path.display()
    );

    NodeAddResult::success(snapshot_path, &ctx.log_path, node_name, node_tag)
}

#[cfg(test)]
mod tests {
    use super::*;
    use httptest::{Expectation, Server, matchers::request, responders::status_code};
    use sha2::{Digest, Sha256};

    fn create_test_tar_zst(content: &[u8]) -> Vec<u8> {
        let mut tar_data = Vec::new();
        {
            let mut tar_builder = tar::Builder::new(&mut tar_data);
            let mut header = tar::Header::new_gnu();
            header.set_size(content.len() as u64);
            header.set_mode(0o644);
            header.set_cksum();
            tar_builder
                .append_data(&mut header, "test.txt", content)
                .unwrap();
            tar_builder.finish().unwrap();
        }
        let mut zst_data = Vec::new();
        let mut encoder = zstd::Encoder::new(&mut zst_data, 0).unwrap();
        std::io::Write::write_all(&mut encoder, &tar_data).unwrap();
        encoder.finish().unwrap();
        zst_data
    }

    fn sha256_hex(data: &[u8]) -> String {
        let hash = Sha256::digest(data);
        encode_hex(hash.as_slice())
    }

    #[test]
    fn test_download_http_bundle_checksum_mismatch() {
        let bundle = create_test_tar_zst(b"hello world");
        let server = Server::run();
        server.expect(
            Expectation::matching(request::method_path("GET", "/bundle.tar.zst"))
                .respond_with(status_code(200).body(bundle)),
        );

        let url = url::Url::parse(&server.url("/bundle.tar.zst").to_string()).unwrap();
        let tmp = tempfile::tempdir().unwrap();
        let dest = tmp.path().join("bundle.tar.zst");

        let wrong_hash = "a".repeat(64);
        let result = download_http_bundle(&url, &dest, Some(&wrong_hash), None);

        assert!(result.is_err());
        let err = result.unwrap_err();
        assert!(
            err.contains("checksum mismatch"),
            "error should mention checksum mismatch, got: {}",
            err
        );
        assert!(
            !dest.exists(),
            "bundle file should be cleaned up on mismatch"
        );
    }

    #[test]
    fn test_download_http_bundle_checksum_ok() {
        let bundle = create_test_tar_zst(b"hello world");
        let correct_hash = sha256_hex(&bundle);
        let server = Server::run();
        server.expect(
            Expectation::matching(request::method_path("GET", "/bundle.tar.zst"))
                .respond_with(status_code(200).body(bundle)),
        );

        let url = url::Url::parse(&server.url("/bundle.tar.zst").to_string()).unwrap();
        let tmp = tempfile::tempdir().unwrap();
        let dest = tmp.path().join("bundle.tar.zst");

        let result = download_http_bundle(&url, &dest, Some(&correct_hash), None);
        assert!(result.is_ok(), "expected Ok, got: {:?}", result);
        assert!(
            dest.exists(),
            "bundle file should exist after successful download"
        );
    }

    #[test]
    fn test_download_http_bundle_no_checksum_skips_verification() {
        let bundle = create_test_tar_zst(b"hello world");
        let server = Server::run();
        server.expect(
            Expectation::matching(request::method_path("GET", "/bundle.tar.zst"))
                .respond_with(status_code(200).body(bundle)),
        );

        let url = url::Url::parse(&server.url("/bundle.tar.zst").to_string()).unwrap();
        let tmp = tempfile::tempdir().unwrap();
        let dest = tmp.path().join("bundle.tar.zst");

        let result = download_http_bundle(&url, &dest, None, None);
        assert!(result.is_ok(), "expected Ok, got: {:?}", result);
        assert!(dest.exists(), "bundle file should exist");
    }
}
