[package]
name = "encoding"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
config = { workspace = true }
daemon-config = { workspace = true }
capnp = "0.26"
capnpc = "0.26"
proc-macro2 = "1.0"
tempfile = "3.8"
indexmap = "2.2"

[build-dependencies]
build-helpers = { workspace = true }

[dev-dependencies]
serde_json5 = "0.2"
