[package]
name = "encoding"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
config = { package = "peppy-config-model", path = "../../../nodes_shared_code/peppyos-shared/peppy-config-model" }
capnp = "0.26"
capnpc = "0.26"
proc-macro2 = "1.0"
tempfile = "3.8"
indexmap = "2.2"

[build-dependencies]
build-helpers = { path = "../../../nodes_shared_code/peppyos-shared/build-helpers" }

[dev-dependencies]
serde_json5 = "0.2"
