use crate::error::Result;
use std::collections::HashMap;
use std::fs;
use std::path::{Path, PathBuf};

include!(concat!(env!("OUT_DIR"), "/precompiled_rust_embed.rs"));

const CACHE_KEY: &str = env!("PEPPY_PRECOMPILED_CACHE_KEY");

/// Deploys the precompiled Rust runtime artifacts to a shared cache directory.
///
/// Artifacts are stored content-addressed at `~/.peppy/libs/rust/<cache_key>/`.
/// Uses file locking to prevent concurrent deployment races.
///
/// All artifacts are deployed, including multiple compilations of the same crate
/// with different feature sets. Each artifact has a unique hash in its filename,
/// so they coexist in the same directory. Rustc resolves the correct version of
/// transitive dependencies by matching metadata hashes embedded in each rlib.
///
/// Returns the path to the deployed artifacts directory.
pub fn deploy_precompiled_runtime() -> Result<PathBuf> {
    let artifacts_dir = config::consts::peppy_data_dir()
        .join("libs/rust")
        .join(CACHE_KEY);

    if artifacts_dir.join(".complete").exists() {
        return Ok(artifacts_dir);
    }

    // Acquire file lock to prevent concurrent deployment
    let lock_path = artifacts_dir.with_extension("lock");
    fs::create_dir_all(lock_path.parent().unwrap())?;
    let lock_file = fs::File::options()
        .read(true)
        .write(true)
        .create(true)
        .truncate(false)
        .open(&lock_path)?;
    lock_file.lock()?;

    // Double-check after acquiring lock
    if artifacts_dir.join(".complete").exists() {
        return Ok(artifacts_dir);
    }

    // Deploy ALL artifacts to a staging directory, then atomically rename.
    // Crates compiled with different feature sets have different filename hashes
    // and coexist safely. Rustc resolves the correct version via metadata hashes.
    let staging_dir = artifacts_dir.with_extension(format!("staging-{}", std::process::id()));
    if staging_dir.exists() {
        fs::remove_dir_all(&staging_dir)?;
    }
    fs::create_dir_all(&staging_dir)?;

    for (filename, contents) in PRECOMPILED_ARTIFACTS {
        fs::write(staging_dir.join(filename), contents)?;
    }

    // Atomic rename
    if artifacts_dir.exists() {
        fs::remove_dir_all(&artifacts_dir)?;
    }
    fs::rename(&staging_dir, &artifacts_dir)?;

    // Write completion marker
    fs::write(artifacts_dir.join(".complete"), "")?;

    Ok(artifacts_dir)
}

/// Generates a `.cargo/config.toml` at `node_dir/.cargo/config.toml` that injects
/// the precompiled runtime artifacts via `-L` and `--extern` rustflags.
///
/// For crates that appear multiple times in the manifest (compiled with different
/// feature sets), the FIRST entry is used for `--extern`. The first compilation
/// corresponds to the full-featured version that peppylib was compiled against;
/// later entries are feature-stripped versions used by proc-macro dependencies.
/// Rustc resolves transitive dependencies by metadata hash via `-L dependency=`.
pub fn generate_cargo_config(node_dir: &Path, artifacts_dir: &Path) -> Result<()> {
    let artifacts_path = artifacts_dir.to_string_lossy();

    // Keep the FIRST entry per extern name. In the build-time compilation order,
    // the first compilation of each crate is the full-featured version in
    // peppylib's direct dependency tree. Later compilations are feature-stripped
    // versions for proc-macro host dependencies.
    let mut extern_map: HashMap<String, String> = HashMap::new();
    for &(crate_name, filename, _kind) in PRECOMPILED_MANIFEST {
        let extern_name = crate_name.replace('-', "_");
        let artifact_path = artifacts_dir.join(filename);
        extern_map
            .entry(extern_name)
            .or_insert_with(|| artifact_path.display().to_string());
    }

    let mut lines = Vec::new();
    lines.push(format!("    \"-L\", \"dependency={artifacts_path}\""));

    let mut sorted_externs: Vec<_> = extern_map.into_iter().collect();
    sorted_externs.sort_by(|a, b| a.0.cmp(&b.0));
    for (extern_name, artifact_path) in sorted_externs {
        lines.push(format!(
            "    \"--extern\", \"{extern_name}={artifact_path}\""
        ));
    }

    let config_content = format!(
        "# Auto-generated by peppy — do not edit.\n\
         [build]\n\
         rustflags = [\n\
         {},\n\
         ]\n",
        lines.join(",\n")
    );

    let cargo_dir = node_dir.join(".cargo");
    fs::create_dir_all(&cargo_dir)?;
    fs::write(cargo_dir.join("config.toml"), config_content)?;

    Ok(())
}

/// Returns the list of crate names provided by the precompiled runtime.
///
/// These crates must NOT appear in the user's Cargo.toml `[dependencies]`.
pub fn precompiled_crate_names() -> impl Iterator<Item = &'static str> {
    PRECOMPILED_MANIFEST
        .iter()
        .map(|&(crate_name, _, _)| crate_name)
}
