use crate::error::Result;
use std::fs;
use std::path::{Path, PathBuf};

include!(concat!(env!("OUT_DIR"), "/precompiled_rust_embed.rs"));

const CACHE_KEY: &str = env!("PEPPY_PRECOMPILED_CACHE_KEY");

/// Deploys the precompiled Rust runtime artifacts to a shared cache directory.
///
/// Artifacts are stored content-addressed at `~/.peppy/libs/rust/<cache_key>/`.
/// Uses file locking to prevent concurrent deployment races.
///
/// All artifacts are deployed, including multiple compilations of the same crate
/// with different feature sets. Each artifact has a unique hash in its filename,
/// so they coexist in the same directory. Rustc resolves the correct version of
/// transitive dependencies by matching metadata hashes embedded in each rlib.
///
/// Returns the path to the deployed artifacts directory.
pub fn deploy_precompiled_runtime() -> Result<PathBuf> {
    let artifacts_dir = config::consts::peppy_data_dir()
        .join("libs/rust")
        .join(CACHE_KEY);

    if artifacts_dir.join(".complete").exists() {
        return Ok(artifacts_dir);
    }

    // Acquire file lock to prevent concurrent deployment
    let lock_path = artifacts_dir.with_extension("lock");
    fs::create_dir_all(lock_path.parent().unwrap())?;
    let lock_file = fs::File::options()
        .read(true)
        .write(true)
        .create(true)
        .truncate(false)
        .open(&lock_path)?;
    lock_file.lock()?;

    // Double-check after acquiring lock
    if artifacts_dir.join(".complete").exists() {
        return Ok(artifacts_dir);
    }

    // Deploy ALL artifacts to a staging directory, then atomically rename.
    // Crates compiled with different feature sets have different filename hashes
    // and coexist safely. Rustc resolves the correct version via metadata hashes.
    let staging_dir = artifacts_dir.with_extension(format!("staging-{}", std::process::id()));
    if staging_dir.exists() {
        fs::remove_dir_all(&staging_dir)?;
    }
    fs::create_dir_all(&staging_dir)?;

    for (filename, contents) in PRECOMPILED_ARTIFACTS {
        fs::write(staging_dir.join(filename), contents)?;
    }

    // Atomic rename
    if artifacts_dir.exists() {
        fs::remove_dir_all(&artifacts_dir)?;
    }
    fs::rename(&staging_dir, &artifacts_dir)?;

    // Write completion marker
    fs::write(artifacts_dir.join(".complete"), "")?;

    Ok(artifacts_dir)
}

/// Writes the precompiled artifacts directory path to a file inside the peppygen
/// crate, so that peppygen's build.rs can read it and emit `-L dependency=`.
pub fn write_precompiled_path(peppygen_dir: &Path, artifacts_dir: &Path) -> Result<()> {
    fs::write(
        peppygen_dir.join("precompiled_dir.txt"),
        artifacts_dir.to_string_lossy().as_bytes(),
    )?;
    Ok(())
}

/// Generates a `build.rs` for the peppygen crate that adds the precompiled
/// artifacts directory to rustc's library search path.
///
/// The build script also publishes the path via `cargo:precompiled_dir=` so that
/// dependent crates (the user's node) can read it through the `DEP_PEPPYGEN_RUNTIME_*`
/// environment variables enabled by peppygen's `links = "peppygen_runtime"` key.
pub fn generate_peppygen_build_rs(peppygen_dir: &Path) -> Result<()> {
    let content = r#"fn main() {
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap();
    let path_file = std::path::Path::new(&manifest_dir).join("precompiled_dir.txt");
    let precompiled_dir = std::fs::read_to_string(&path_file)
        .expect("precompiled_dir.txt not found — run `peppy node sync` first");
    let precompiled_dir = precompiled_dir.trim();

    // 'crate' makes extern crate declarations resolve (direct deps).
    // 'dependency' lets transitive deps resolve each other.
    println!("cargo:rustc-link-search=crate={precompiled_dir}");
    println!("cargo:rustc-link-search=dependency={precompiled_dir}");
    println!("cargo:precompiled_dir={precompiled_dir}");
    println!("cargo:rerun-if-changed=precompiled_dir.txt");
}
"#;
    fs::write(peppygen_dir.join("build.rs"), content)?;
    Ok(())
}

/// Generates a build script for the node that reads the precompiled artifacts
/// directory from peppygen's build-script metadata and adds it to rustc's
/// library search path.
///
/// Placed at `.peppy/build.rs` so generated files stay under the `.peppy/`
/// directory (which is typically gitignored).
pub fn generate_node_build_rs(node_dir: &Path) -> Result<()> {
    let content = r#"// Auto-generated by peppy — do not edit.
fn main() {
    let precompiled_dir = std::env::var("DEP_PEPPYGEN_RUNTIME_PRECOMPILED_DIR")
        .expect("DEP_PEPPYGEN_RUNTIME_PRECOMPILED_DIR not set — ensure peppygen has links = \"peppygen_runtime\"");

    println!("cargo:rustc-link-search=dependency={precompiled_dir}");
}
"#;
    let peppy_dir = node_dir.join(".peppy");
    fs::create_dir_all(&peppy_dir)?;
    fs::write(peppy_dir.join("build.rs"), content)?;
    Ok(())
}

/// Removes the legacy `.cargo/config.toml` that was previously generated by
/// peppy. This file is no longer needed since precompiled deps are now injected
/// via build.rs instead of global rustflags.
pub fn remove_legacy_cargo_config(node_dir: &Path) -> Result<()> {
    let config_path = node_dir.join(".cargo/config.toml");
    if config_path.exists() {
        fs::remove_file(&config_path)?;
        // Remove .cargo dir if now empty
        let cargo_dir = node_dir.join(".cargo");
        if cargo_dir.read_dir()?.next().is_none() {
            fs::remove_dir(&cargo_dir)?;
        }
    }
    Ok(())
}

/// Returns the list of crate names provided by the precompiled runtime.
///
/// These crates must NOT appear in the user's Cargo.toml `[dependencies]`.
pub fn precompiled_crate_names() -> impl Iterator<Item = &'static str> {
    PRECOMPILED_MANIFEST
        .iter()
        .map(|&(crate_name, _, _)| crate_name)
}
