[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "first_node"
version = "0.1.0"
description = "first_node peppy node"
requires-python = ">=3.11"
dependencies = ["peppygen"]

[project.scripts]
first_node = "first_node.__main__:main"

[tool.hatch.build.targets.wheel]
packages = ["src/first_node"]

[dependency-groups]
dev = []

[tool.uv.sources]
peppygen = { path = ".peppy/libs/peppygen" }