[package]
name = "federation"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
config = { workspace = true }
daemon-config = { workspace = true }
json5-pretty = { workspace = true }
pmi = { workspace = true, features = ["zenoh"] }
rcgen = { version = "0.14.8", features = ["x509-parser"] }
serde = { version = "1", features = ["derive"] }
serde_json5 = "0.2"
thiserror = "2.0"
time = "0.3"

[dev-dependencies]
tempfile = "3.8"
x509-parser = "0.18"
