[package]
name = "peppycl"
version.workspace = true
edition.workspace = true
homepage = "https://dev.peppy.bot"
description = "The peppyOS control library"
license = "MIT OR Apache-2.0"
readme = "Readme.md"

[dependencies]
pmi = { path = "../pmi" }
thiserror = "2.0.14" # Avoid Anyhow in this crate
tokio = "1.47.0"
zenoh = "1.5.0"