[package]
name = "core-node-api"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
# This is the only crate that is allowed to be imported to avoid future circular dependencies
config = { path = "../config-internal" }
capnp = "0.25"
bytes = "1.10"
chrono = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json5 = "0.2"
thiserror = "2.0"
url = "2"
gix-url = "0.36"

[build-dependencies]
build-helpers = { path = "../build-helpers-internal" }
capnpc = "0.25"

[dev-dependencies]
tempfile = "3.10"
