#!/usr/bin/env bash
# Buildkite port of .github/workflows/docs-drift.yml.
#
# Runs only for the release PR that merges dev into main (gated by the step
# `if` in pipeline.yml). Checks whether docs/ is in sync with the code
# changes; when it is not, regenerates the docs and opens a follow-up PR
# against the contributor branch (dev).
#
# The Actions version ran only on PR opened/reopened. Buildkite cannot see the
# PR action type, so this runs on every release-PR build and is idempotent
# instead: the auto branch is force-pushed each time and the PR is created
# only if one is not already open — the follow-up PR stays in sync instead of
# going stale after the first push.
set -euo pipefail

PR_NUMBER="${BUILDKITE_PULL_REQUEST:?docs-drift only runs on pull-request builds}"
BASE_BRANCH="${BUILDKITE_PULL_REQUEST_BASE_BRANCH:?}" # main
HEAD_BRANCH="${BUILDKITE_BRANCH:?}"                   # dev
HEAD_SHA="${BUILDKITE_COMMIT:?}"

# Isolate git global config from the agent user so the doc scripts and the
# commit below cannot pick up the host user's identity or settings.
GIT_CONFIG_GLOBAL="$(mktemp "${TMPDIR:-/tmp}/peppy-gitconfig.XXXXXX")"
export GIT_CONFIG_GLOBAL
trap 'rm -f "${GIT_CONFIG_GLOBAL}"' EXIT

echo "--- :mag: check docs are up to date"
git fetch -q origin "refs/heads/${BASE_BRANCH}:refs/remotes/origin/${BASE_BRANCH}"
if pixi run --manifest-path scripts is-doc-up-to-date "origin/${BASE_BRANCH}" "${HEAD_SHA}"; then
  echo "docs are in sync; nothing to do"
  exit 0
fi

echo "--- :memo: update docs"
pixi run --manifest-path scripts update-docs "origin/${BASE_BRANCH}" "${HEAD_SHA}"

echo "--- :github: follow-up PR against ${HEAD_BRANCH}"
DOCS_BRANCH="auto/docs-update-${PR_NUMBER}"

# Commit only the regenerated docs (was add-paths: docs/**) onto a branch cut
# from the release-PR head.
git switch -C "${DOCS_BRANCH}"
git add -- docs/
if git diff --cached --quiet; then
  echo "update-docs made no changes under docs/; nothing to push"
  exit 0
fi
git -c user.name="${PEPPY_BOT_GIT_NAME:-peppy-bot}" \
    -c user.email="${PEPPY_BOT_GIT_EMAIL:-peppy-bot@users.noreply.github.com}" \
    commit -m "docs: auto-sync with code changes"

# Push and open the PR as the bot (was secrets.PEPPY_BOT_TOKEN). The token
# comes from the agent environment, or from Buildkite secrets storage when the
# env var is absent.
PEPPY_BOT_TOKEN="${PEPPY_BOT_TOKEN:-$(buildkite-agent secret get peppy_bot_token)}"
export PEPPY_BOT_TOKEN

REPO_SLUG="$(git remote get-url origin | sed -E 's#^(git@github\.com:|https://github\.com/)##; s#\.git$##')"

# Push over https with an ephemeral credential helper: the checkout remote may
# be ssh with a read-only deploy key, and this keeps the token off argv and
# out of .git/config.
git -c credential.helper= \
    -c credential.helper='!f() { echo "username=x-access-token"; echo "password=${PEPPY_BOT_TOKEN}"; }; f' \
    push --force "https://github.com/${REPO_SLUG}.git" "HEAD:refs/heads/${DOCS_BRANCH}"

export GH_TOKEN="${PEPPY_BOT_TOKEN}"
existing="$(gh pr list --repo "${REPO_SLUG}" --head "${DOCS_BRANCH}" --base "${HEAD_BRANCH}" \
  --state open --json number --jq '.[0].number // empty')"
if [[ -n "${existing}" ]]; then
  echo "follow-up PR #${existing} already open; branch refreshed by the force-push"
else
  gh pr create --repo "${REPO_SLUG}" \
    --base "${HEAD_BRANCH}" --head "${DOCS_BRANCH}" \
    --title "docs: sync with PR #${PR_NUMBER}" \
    --body "$(printf 'Automated doc update generated by `scripts/docs/update_docs.py`\nin response to code changes in #%s.' "${PR_NUMBER}")"
fi
