[package]
name = "peppy"
version.workspace = true
edition.workspace = true

[dependencies]
bytes = "1"
askama = "0.14.0" # To help out on code generation (py and Rust) to create interface libs in .pixi envs or use (quote! macro + syn + prettyplease)
# https://docs.rs/quote/latest/quote/
capnp = "0.21.4" # ROS 2 uses CDR (Common Data Representation) for message serialization/deserialization
clap = { version = "4.5.42", features = ["derive"] }
starlark = "0.13.0" # To parse peppy.star
tokio = "1.47.0"
zenoh = "1.5.0"
tracing = "0.1.41"
derive_more = { version = "2", features = ["from"] }
rayon = "1.11.0"
service-manager = "0.8.0"

[dev-dependencies]
tempfile = "3.8"

[features]
default = ["build_pixi", "build_zenoh"]
# Feature to enable building pixi from source
build_pixi = []
# Feature to enable building zenoh from source
build_zenoh = []
